import{describe,expect,it}from'vitest';import{calculateAverageSpeed,calculatePace,cardioDateTimeDisplayToIso,deriveWorkoutType,isFasterPace,isoToCardioDateTimeDisplay,kilometersToMiles,maskCardioDateInput,maskCardioTimeInput,milesToKilometers,summarizeCardio,validateCardioInput}from'./cardioService';import type{CardioSession,CardioSessionInput}from'@/types/cardio';import type{ActiveWorkout}from'@/types/workout';
const input:CardioSessionInput={workoutId:null,workoutExerciseId:null,activityType:'running',date:'2026-01-01',durationSeconds:1800,distanceKm:5,calories:300,averageHeartRate:150,maxHeartRate:170,elevationGain:20,cadence:170,rounds:null,notes:null};const session:CardioSession={id:'c',...input,averagePaceSecondsPerKm:360,averageSpeedKph:10,createdAt:'',updatedAt:''};const workout:Pick<ActiveWorkout,'exercises'>={exercises:[]};
describe('cardio calculations',()=>{it('calculates pace',()=>expect(calculatePace(1800,5)).toBe(360));it('calculates average speed',()=>expect(calculateAverageSpeed(1800,5)).toBe(10));it('returns null without valid distance',()=>expect(calculatePace(100,null)).toBeNull());it('converts miles and kilometers without corrupting raw values',()=>expect(kilometersToMiles(milesToKilometers(10))).toBeCloseTo(10));it('validates duration and negative fields',()=>{expect(()=>validateCardioInput({...input,durationSeconds:0})).toThrow('Duration');expect(()=>validateCardioInput({...input,distanceKm:-1})).toThrow('negative');});it('derives cardio and mixed types from content',()=>{expect(deriveWorkoutType(workout,1)).toBe('cardio');expect(deriveWorkoutType({...workout,exercises:[{sets:[{}]}]as ActiveWorkout['exercises']},1)).toBe('mixed');});it('summarizes cardio independently from lifting volume',()=>expect(summarizeCardio([session,{...session,id:'d',durationSeconds:3600,distanceKm:10,averagePaceSecondsPerKm:360}])).toMatchObject({sessionCount:2,totalDurationSeconds:5400,totalDistanceKm:15,longestDistanceKm:10}));it('fastest pace is lower and requires at least 0.5 km',()=>{expect(isFasterPace(300,.4,360)).toBe(false);expect(isFasterPace(300,5,360)).toBe(true);expect(isFasterPace(400,5,360)).toBe(false);});});
describe('cardio date/time input',()=>{
  it('masks a date with auto-inserted slashes',()=>{expect(maskCardioDateInput('1')).toBe('1');expect(maskCardioDateInput('12')).toBe('12/');expect(maskCardioDateInput('1231')).toBe('12/31/');expect(maskCardioDateInput('12312026')).toBe('12/31/2026');});
  it('allows backspace across an automatic date separator',()=>expect(maskCardioDateInput('12','12/')).toBe('1'));
  it('masks a time with an auto-inserted colon',()=>{expect(maskCardioTimeInput('1')).toBe('1');expect(maskCardioTimeInput('14')).toBe('14:');expect(maskCardioTimeInput('1430')).toBe('14:30');});
  it('allows backspace across an automatic time separator',()=>expect(maskCardioTimeInput('14','14:')).toBe('1'));
  it('splits an ISO instant into display date and time (local)',()=>expect(isoToCardioDateTimeDisplay(new Date(2026,2,5,14,30).toISOString())).toEqual({date:'03/05/2026',time:'14:30'}));
  it('combines display date and time back into ISO',()=>{const iso=cardioDateTimeDisplayToIso('03/05/2026','14:30');expect(isoToCardioDateTimeDisplay(iso)).toEqual({date:'03/05/2026',time:'14:30'});});
  it('rejects an invalid date or time',()=>{expect(()=>cardioDateTimeDisplayToIso('13/05/2026','14:30')).toThrow(/date/);expect(()=>cardioDateTimeDisplayToIso('03/05/2026','25:00')).toThrow(/time/);});
});
