import { subDays, subMonths, subYears } from 'date-fns';
import { useFocusEffect } from 'expo-router';
import { useCallback, useState } from 'react';
import { Alert, StyleSheet, Text, View } from 'react-native';
import { AppButton } from '@/components/AppButton'; import { AppInput } from '@/components/AppInput'; import { AppScreen } from '@/components/AppScreen'; import { FilterChip } from '@/components/FilterChip'; import { Header } from '@/components/Header'; import { MeasurementDifferenceBadge } from '@/components/MeasurementDifferenceBadge';
import { colors } from '@/constants/colors'; import { radius, spacing } from '@/constants/spacing'; import { typography } from '@/constants/typography'; import { useSettings } from '@/contexts/SettingsContext'; import { useDatabase } from '@/hooks/useDatabase'; import { createWeightEntry, deleteWeightEntry, getWeightHistory } from '@/repositories/bodyWeightRepository'; import type { BodyWeightEntry } from '@/types/body'; import { displayToKilograms, kilogramsToDisplay } from '@/utils/units';

type Filter='30d'|'3m'|'6m'|'1y'|'all';
const fromFor=(filter:Filter):string|undefined=>{const now=new Date();const date=filter==='30d'?subDays(now,30):filter==='3m'?subMonths(now,3):filter==='6m'?subMonths(now,6):filter==='1y'?subYears(now,1):null;return date?.toISOString()};
export default function WeightHistory(){const db=useDatabase();const{settings}=useSettings();const[rows,setRows]=useState<BodyWeightEntry[]>([]);const[filter,setFilter]=useState<Filter>('3m');const[weight,setWeight]=useState('');const[notes,setNotes]=useState('');const load=useCallback(()=>void getWeightHistory(db,fromFor(filter)).then(setRows),[db,filter]);useFocusEffect(load);const save=async()=>{try{await createWeightEntry(db,{weightKg:displayToKilograms(Number(weight),settings.weightUnit),measuredAt:new Date().toISOString(),notes:notes.trim()||null});setWeight('');setNotes('');load()}catch(e){Alert.alert('Could not save weight',e instanceof Error?e.message:'Enter a valid weight.')}};const first=rows[rows.length-1];return <AppScreen scroll header={<Header title="Weight History"/>}><AppInput accessibilityLabel={`Weight in ${settings.weightUnit}`} label={`Weight (${settings.weightUnit})`} keyboardType="decimal-pad" value={weight} onChangeText={setWeight}/><AppInput label="Notes" value={notes} onChangeText={setNotes}/><AppButton label="Add weight entry" onPress={()=>void save()}/><View style={styles.filters}>{([['30d','30 days'],['3m','3 months'],['6m','6 months'],['1y','1 year'],['all','All time']]as const).map(([id,label])=><FilterChip key={id} label={label} selected={filter===id} onPress={()=>setFilter(id)}/>)}</View>{rows.length===0?<Text style={styles.muted}>Add your first weight entry to start tracking progress.</Text>:rows.map((row,index)=>{const change=rows[index+1]?kilogramsToDisplay(row.weightKg-rows[index+1].weightKg,settings.weightUnit):null;const fromFirst=first&&first.id!==row.id?kilogramsToDisplay(row.weightKg-first.weightKg,settings.weightUnit):null;return <View key={row.id} style={styles.card}><View><Text style={styles.value}>{kilogramsToDisplay(row.weightKg,settings.weightUnit).toFixed(1)} {settings.weightUnit}</Text><Text style={styles.muted}>{new Date(row.measuredAt).toLocaleDateString()}{row.notes?` · ${row.notes}`:''}</Text>{fromFirst!=null?<Text style={styles.muted}>{fromFirst>=0?'+':'−'}{Math.abs(fromFirst).toFixed(1)} {settings.weightUnit} from first in range</Text>:null}</View>{change!=null?<MeasurementDifferenceBadge value={change} unit={settings.weightUnit}/>:null}<AppButton label="Delete weight entry" variant="danger" onPress={()=>Alert.alert('Delete weight entry?','This cannot be undone.',[{text:'Cancel'},{text:'Delete',style:'destructive',onPress:()=>void deleteWeightEntry(db,row.id).then(load)}])}/></View>})}</AppScreen>}
const styles=StyleSheet.create({card:{padding:spacing.md,gap:spacing.sm,borderRadius:radius.md,backgroundColor:colors.surface},value:{...typography.heading,color:colors.text},muted:{...typography.caption,color:colors.textMuted},filters:{flexDirection:'row',flexWrap:'wrap',gap:spacing.sm}});
