export const cardioActivityTypes = ['running', 'treadmill_running', 'cycling', 'stationary_cycling', 'walking', 'hiking', 'rowing', 'elliptical', 'stair_climber', 'swimming', 'jump_rope', 'cricket', 'circuit', 'other'] as const;
export type CardioActivityType = (typeof cardioActivityTypes)[number];
export type CardioTimerStatus = 'running' | 'paused' | 'finished';
export interface CardioSession { id: string; workoutId: string | null; workoutExerciseId: string | null; activityType: CardioActivityType; date: string; durationSeconds: number; distanceKm: number | null; calories: number | null; averageHeartRate: number | null; maxHeartRate: number | null; elevationGain: number | null; averagePaceSecondsPerKm: number | null; averageSpeedKph: number | null; cadence: number | null; rounds: number | null; notes: string | null; createdAt: string; updatedAt: string; }
export type CardioSessionInput = Omit<CardioSession, 'id' | 'averagePaceSecondsPerKm' | 'averageSpeedKph' | 'createdAt' | 'updatedAt'>;
export interface CardioSessionSummary { sessionCount: number; totalDurationSeconds: number; totalDistanceKm: number; averageDurationSeconds: number; averageDistanceKm: number; averagePaceSecondsPerKm: number | null; longestDurationSeconds: number; longestDistanceKm: number; fastestPaceSecondsPerKm: number | null; }
export interface CardioChartPoint { date: string; durationSeconds: number; distanceKm: number | null; paceSecondsPerKm: number | null; averageHeartRate: number | null; }
export interface CardioTimerState { startedAt: string; pausedAt: string | null; totalPausedSeconds: number; status: CardioTimerStatus; }
export const cardioRecordTypes=['longest_distance','longest_duration','fastest_pace','highest_average_speed','highest_calories','highest_elevation_gain']as const;export type CardioRecordType=typeof cardioRecordTypes[number];export interface CardioPersonalRecord{id:string;activityType:CardioActivityType;recordType:CardioRecordType;value:number;cardioSessionId:string;achievedAt:string;}
