import type{SQLiteDatabase}from'expo-sqlite';import{validateMeasurementEntry}from'@/services/bodyMeasurementService';import type{BodyMeasurementEntry,BodyMeasurementEntryInput,BodyMeasurementValue,MeasurementType}from'@/types/body';import{createId}from'@/utils/ids';import{AppError,toAppError}from'@/utils/errors';import{LOCAL_PROFILE_ID}from'./userProfileRepository';import{synchronizeCurrentProfileWeight}from'./bodyWeightRepository';
interface EntryRow{id:string;profile_id:string;measured_at:string;body_weight_kg:number|null;notes:string|null;created_at:string;updated_at:string}interface ValueRow{id:string;entry_id:string;measurement_type_id:string;value_cm:number;created_at:string;updated_at:string;type_id:string;key:string;display_name:string;category:string;default_unit:'cm';is_builtin:number;is_active:number;sort_order:number;type_created_at:string;type_updated_at:string}
const type=(r:ValueRow):MeasurementType=>({id:r.type_id,key:r.key,displayName:r.display_name,category:r.category,defaultUnit:r.default_unit,isBuiltin:Boolean(r.is_builtin),isActive:Boolean(r.is_active),sortOrder:r.sort_order,createdAt:r.type_created_at,updatedAt:r.type_updated_at});const value=(r:ValueRow):BodyMeasurementValue=>({id:r.id,entryId:r.entry_id,measurementTypeId:r.measurement_type_id,valueCm:r.value_cm,createdAt:r.created_at,updatedAt:r.updated_at,measurementType:type(r)});
async function hydrate(db:SQLiteDatabase,row:EntryRow):Promise<BodyMeasurementEntry>{const values=await db.getAllAsync<ValueRow>(`SELECT bmv.*,mt.id type_id,mt.key,mt.display_name,mt.category,mt.default_unit,mt.is_builtin,mt.is_active,mt.sort_order,mt.created_at type_created_at,mt.updated_at type_updated_at FROM body_measurement_values bmv JOIN measurement_types mt ON mt.id=bmv.measurement_type_id WHERE bmv.entry_id=? ORDER BY mt.sort_order`,[row.id]);return{id:row.id,profileId:row.profile_id,measuredAt:row.measured_at,bodyWeightKg:row.body_weight_kg,notes:row.notes,createdAt:row.created_at,updatedAt:row.updated_at,values:values.map(value)};}
async function writeValues(tx:SQLiteDatabase,entryId:string,values:BodyMeasurementEntryInput['values'],now:string){for(const item of values)await tx.runAsync('INSERT INTO body_measurement_values (id,entry_id,measurement_type_id,value_cm,created_at,updated_at) VALUES (?,?,?,?,?,?)',[createId('measurement_value'),entryId,item.measurementTypeId,item.valueCm,now,now]);}
const weightLink=(entryId:string)=>`Body measurement entry:${entryId}`;
export async function createMeasurementEntry(db:SQLiteDatabase,input:BodyMeasurementEntryInput):Promise<string>{const data=validateMeasurementEntry(input);const duplicate=await db.getFirstAsync<{id:string}>('SELECT id FROM body_measurement_entries WHERE profile_id=? AND date(measured_at)=date(?) LIMIT 1',[LOCAL_PROFILE_ID,data.measuredAt]);if(duplicate)throw new AppError('A measurement entry already exists for this date. Edit or duplicate that entry instead.');const id=createId('measurement');const now=new Date().toISOString();try{await db.withExclusiveTransactionAsync(async tx=>{await tx.runAsync('INSERT INTO body_measurement_entries (id,profile_id,measured_at,body_weight_kg,notes,created_at,updated_at) VALUES (?,?,?,?,?,?,?)',[id,LOCAL_PROFILE_ID,data.measuredAt,data.bodyWeightKg,data.notes,now,now]);await writeValues(tx,id,data.values,now);if(data.bodyWeightKg!=null)await tx.runAsync('INSERT INTO body_weight_entries (id,profile_id,weight_kg,measured_at,notes,created_at,updated_at) VALUES (?,?,?,?,?,?,?)',[createId('weight'),LOCAL_PROFILE_ID,data.bodyWeightKg,data.measuredAt,weightLink(id),now,now]);await synchronizeCurrentProfileWeight(tx);});return id;}catch(e){throw toAppError(e,'Could not save body measurements.');}}
/** The linked weight row is updated in the same transaction so charts and the profile snapshot agree. */
export async function updateMeasurementEntry(db:SQLiteDatabase,id:string,input:BodyMeasurementEntryInput):Promise<void>{const data=validateMeasurementEntry(input);const now=new Date().toISOString();try{await db.withExclusiveTransactionAsync(async tx=>{await tx.runAsync('UPDATE body_measurement_entries SET measured_at=?,body_weight_kg=?,notes=?,updated_at=? WHERE id=?',[data.measuredAt,data.bodyWeightKg,data.notes,now,id]);await tx.runAsync('DELETE FROM body_measurement_values WHERE entry_id=?',[id]);await writeValues(tx,id,data.values,now);const linked=await tx.getFirstAsync<{id:string}>('SELECT id FROM body_weight_entries WHERE notes=?',[weightLink(id)]);if(data.bodyWeightKg==null&&linked)await tx.runAsync('DELETE FROM body_weight_entries WHERE id=?',[linked.id]);else if(data.bodyWeightKg!=null&&linked)await tx.runAsync('UPDATE body_weight_entries SET weight_kg=?,measured_at=?,updated_at=? WHERE id=?',[data.bodyWeightKg,data.measuredAt,now,linked.id]);else if(data.bodyWeightKg!=null)await tx.runAsync('INSERT INTO body_weight_entries (id,profile_id,weight_kg,measured_at,notes,created_at,updated_at) VALUES (?,?,?,?,?,?,?)',[createId('weight'),LOCAL_PROFILE_ID,data.bodyWeightKg,data.measuredAt,weightLink(id),now,now]);await synchronizeCurrentProfileWeight(tx);});}catch(e){throw toAppError(e,'Could not update body measurements.');}}
export async function deleteMeasurementEntry(db:SQLiteDatabase,id:string):Promise<void>{await db.withExclusiveTransactionAsync(async tx=>{await tx.runAsync('DELETE FROM body_weight_entries WHERE notes=?',[weightLink(id)]);await tx.runAsync('DELETE FROM body_measurement_entries WHERE id=?',[id]);await synchronizeCurrentProfileWeight(tx);});}
export async function getMeasurementEntryById(db:SQLiteDatabase,id:string):Promise<BodyMeasurementEntry|null>{const row=await db.getFirstAsync<EntryRow>('SELECT * FROM body_measurement_entries WHERE id=?',[id]);return row?hydrate(db,row):null;}
export async function getMeasurementHistory(db:SQLiteDatabase):Promise<BodyMeasurementEntry[]>{const rows=await db.getAllAsync<EntryRow>('SELECT * FROM body_measurement_entries WHERE profile_id=? ORDER BY measured_at DESC',[LOCAL_PROFILE_ID]);return Promise.all(rows.map(row=>hydrate(db,row)));}
export async function getLatestMeasurementEntry(db:SQLiteDatabase):Promise<BodyMeasurementEntry|null>{const row=await db.getFirstAsync<EntryRow>('SELECT * FROM body_measurement_entries WHERE profile_id=? ORDER BY measured_at DESC LIMIT 1',[LOCAL_PROFILE_ID]);return row?hydrate(db,row):null;}
export async function getPreviousMeasurementEntry(db:SQLiteDatabase,before:string):Promise<BodyMeasurementEntry|null>{const row=await db.getFirstAsync<EntryRow>('SELECT * FROM body_measurement_entries WHERE profile_id=? AND measured_at<? ORDER BY measured_at DESC LIMIT 1',[LOCAL_PROFILE_ID,before]);return row?hydrate(db,row):null;}
export async function duplicateMeasurementEntry(db:SQLiteDatabase,id:string):Promise<BodyMeasurementEntryInput|null>{const entry=await getMeasurementEntryById(db,id);return entry?{measuredAt:new Date().toISOString(),bodyWeightKg:entry.bodyWeightKg,notes:entry.notes,values:entry.values.map(v=>({measurementTypeId:v.measurementTypeId,valueCm:v.valueCm}))}:null;}
export async function getMeasurementValuesByType(db:SQLiteDatabase,typeId:string):Promise<{measuredAt:string;valueCm:number}[]>{return db.getAllAsync('SELECT e.measured_at measuredAt,v.value_cm valueCm FROM body_measurement_values v JOIN body_measurement_entries e ON e.id=v.entry_id WHERE v.measurement_type_id=? ORDER BY e.measured_at',[typeId]);}
export async function getComparisonEntries(db:SQLiteDatabase,currentId:string,previousId:string):Promise<[BodyMeasurementEntry,BodyMeasurementEntry]|null>{const [a,b]=await Promise.all([getMeasurementEntryById(db,currentId),getMeasurementEntryById(db,previousId)]);return a&&b?[a,b]:null;}
