import type{SQLiteDatabase}from'expo-sqlite';import type{BodyWeightEntry,BodyWeightEntryInput}from'@/types/body';import{LOCAL_PROFILE_ID}from'./userProfileRepository';import{createId}from'@/utils/ids';import{AppError,toAppError}from'@/utils/errors';
interface Row{id:string;profile_id:string;weight_kg:number;measured_at:string;notes:string|null;created_at:string;updated_at:string}const map=(r:Row):BodyWeightEntry=>({id:r.id,profileId:r.profile_id,weightKg:r.weight_kg,measuredAt:r.measured_at,notes:r.notes,createdAt:r.created_at,updatedAt:r.updated_at});
function valid(input:BodyWeightEntryInput){if(!Number.isFinite(input.weightKg)||input.weightKg<=0||input.weightKg>1000)throw new AppError('Enter a valid positive weight.');const date=new Date(input.measuredAt);if(Number.isNaN(date.getTime())||date.getTime()>Date.now())throw new AppError('Enter a valid measurement date.');}
/** Latest weight wins; deleting or backdating an entry re-synchronizes the profile snapshot. */
export async function synchronizeCurrentProfileWeight(db:SQLiteDatabase):Promise<void>{const latest=await db.getFirstAsync<{weight_kg:number}>('SELECT weight_kg FROM body_weight_entries WHERE profile_id=? ORDER BY measured_at DESC,created_at DESC LIMIT 1',[LOCAL_PROFILE_ID]);await db.runAsync('UPDATE user_profile SET current_weight_kg=?,updated_at=? WHERE id=?',[latest?.weight_kg??null,new Date().toISOString(),LOCAL_PROFILE_ID]);}
export async function createWeightEntry(db:SQLiteDatabase,input:BodyWeightEntryInput):Promise<string>{valid(input);const id=createId('weight');const now=new Date().toISOString();try{await db.withExclusiveTransactionAsync(async tx=>{await tx.runAsync('INSERT INTO body_weight_entries (id,profile_id,weight_kg,measured_at,notes,created_at,updated_at) VALUES (?,?,?,?,?,?,?)',[id,LOCAL_PROFILE_ID,input.weightKg,input.measuredAt,input.notes,now,now]);await synchronizeCurrentProfileWeight(tx);});return id;}catch(e){throw toAppError(e,'Could not save this weight entry.');}}
export async function updateWeightEntry(db:SQLiteDatabase,id:string,input:BodyWeightEntryInput):Promise<void>{valid(input);await db.withExclusiveTransactionAsync(async tx=>{await tx.runAsync('UPDATE body_weight_entries SET weight_kg=?,measured_at=?,notes=?,updated_at=? WHERE id=?',[input.weightKg,input.measuredAt,input.notes,new Date().toISOString(),id]);await synchronizeCurrentProfileWeight(tx);});}
export async function deleteWeightEntry(db:SQLiteDatabase,id:string):Promise<void>{await db.withExclusiveTransactionAsync(async tx=>{await tx.runAsync('DELETE FROM body_weight_entries WHERE id=?',[id]);await synchronizeCurrentProfileWeight(tx);});}
export async function getWeightEntryById(db:SQLiteDatabase,id:string):Promise<BodyWeightEntry|null>{const r=await db.getFirstAsync<Row>('SELECT * FROM body_weight_entries WHERE id=?',[id]);return r?map(r):null;}
export async function getLatestWeightEntry(db:SQLiteDatabase):Promise<BodyWeightEntry|null>{const r=await db.getFirstAsync<Row>('SELECT * FROM body_weight_entries WHERE profile_id=? ORDER BY measured_at DESC,created_at DESC LIMIT 1',[LOCAL_PROFILE_ID]);return r?map(r):null;}
export async function getWeightHistory(db:SQLiteDatabase,from?:string):Promise<BodyWeightEntry[]>{const rows=from?await db.getAllAsync<Row>('SELECT * FROM body_weight_entries WHERE profile_id=? AND measured_at>=? ORDER BY measured_at DESC',[LOCAL_PROFILE_ID,from]):await db.getAllAsync<Row>('SELECT * FROM body_weight_entries WHERE profile_id=? ORDER BY measured_at DESC',[LOCAL_PROFILE_ID]);return rows.map(map);}
export const getWeightEntriesByDateRange=async(db:SQLiteDatabase,from:string,to:string)=>(await db.getAllAsync<Row>('SELECT * FROM body_weight_entries WHERE profile_id=? AND measured_at BETWEEN ? AND ? ORDER BY measured_at',[LOCAL_PROFILE_ID,from,to])).map(map);
