import type { SQLiteDatabase } from 'expo-sqlite'; import type { CardioActivityType, CardioSession, CardioSessionInput, CardioSessionSummary } from '@/types/cardio'; import { calculateAverageSpeed, calculatePace, summarizeCardio, validateCardioInput } from '../services/cardioService'; import { AppError, toAppError } from '../utils/errors'; import { createId } from '../utils/ids'; import { detectAndSaveCardioRecords } from './cardioPersonalRecordRepository';
interface Row { id: string; workout_id: string | null; workout_exercise_id: string | null; activity_type: CardioActivityType; date: string; duration_seconds: number; distance: number | null; calories: number | null; average_heart_rate: number | null; max_heart_rate: number | null; elevation_gain: number | null; average_pace_seconds_per_unit: number | null; average_speed: number | null; cadence: number | null; rounds: number | null; notes: string | null; created_at: string; updated_at: string; }
const map = (row: Row): CardioSession => ({ id: row.id, workoutId: row.workout_id, workoutExerciseId: row.workout_exercise_id, activityType: row.activity_type, date: row.date, durationSeconds: row.duration_seconds, distanceKm: row.distance, calories: row.calories, averageHeartRate: row.average_heart_rate, maxHeartRate: row.max_heart_rate, elevationGain: row.elevation_gain, averagePaceSecondsPerKm: row.average_pace_seconds_per_unit, averageSpeedKph: row.average_speed, cadence: row.cadence, rounds: row.rounds, notes: row.notes, createdAt: row.created_at, updatedAt: row.updated_at });
const values = (input: CardioSessionInput, id: string, now: string) => [id, input.workoutId, input.workoutExerciseId, input.activityType, input.date, input.durationSeconds, input.distanceKm, input.calories, input.averageHeartRate, input.maxHeartRate, input.elevationGain, calculatePace(input.durationSeconds, input.distanceKm), calculateAverageSpeed(input.durationSeconds, input.distanceKm), input.cadence, input.rounds, input.notes, now, now] as const;
export async function createCardioSession(db: SQLiteDatabase, input: CardioSessionInput): Promise<CardioSession> { validateCardioInput(input); const id = createId('cardio'); const now = new Date().toISOString(); await db.runAsync(`INSERT INTO cardio_sessions (id, workout_id, workout_exercise_id, activity_type, date, duration_seconds, distance, calories, average_heart_rate, max_heart_rate, elevation_gain, average_pace_seconds_per_unit, average_speed, cadence, rounds, notes, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`, [...values(input, id, now)]); const result = await getCardioSessionById(db, id); if (!result) throw new AppError('Cardio session was not created.'); await detectAndSaveCardioRecords(db,result);return result; }
export async function updateCardioSession(db: SQLiteDatabase, id: string, input: CardioSessionInput): Promise<void> { validateCardioInput(input); const now = new Date().toISOString(); await db.runAsync(`UPDATE cardio_sessions SET workout_id=?, workout_exercise_id=?, activity_type=?, date=?, duration_seconds=?, distance=?, calories=?, average_heart_rate=?, max_heart_rate=?, elevation_gain=?, average_pace_seconds_per_unit=?, average_speed=?, cadence=?, rounds=?, notes=?, updated_at=? WHERE id=?`, [input.workoutId, input.workoutExerciseId, input.activityType, input.date, input.durationSeconds, input.distanceKm, input.calories, input.averageHeartRate, input.maxHeartRate, input.elevationGain, calculatePace(input.durationSeconds, input.distanceKm), calculateAverageSpeed(input.durationSeconds, input.distanceKm), input.cadence, input.rounds, input.notes, now, id]); }
export async function deleteCardioSession(db: SQLiteDatabase, id: string): Promise<void> { await db.runAsync('DELETE FROM cardio_sessions WHERE id = ?', [id]); }
export async function getCardioSessionById(db: SQLiteDatabase, id: string): Promise<CardioSession | null> { const row = await db.getFirstAsync<Row>('SELECT * FROM cardio_sessions WHERE id = ?', [id]); return row ? map(row) : null; }
export async function getCardioSessionsByWorkout(db: SQLiteDatabase, workoutId: string): Promise<CardioSession[]> { return (await db.getAllAsync<Row>('SELECT * FROM cardio_sessions WHERE workout_id = ? ORDER BY date', [workoutId])).map(map); }
export async function getRecentCardioSessions(db: SQLiteDatabase, limit = 20): Promise<CardioSession[]> { return (await db.getAllAsync<Row>('SELECT * FROM cardio_sessions ORDER BY date DESC LIMIT ?', [limit])).map(map); }
export async function getCardioSessionsByDateRange(db: SQLiteDatabase, from: string, to: string, activityType?: CardioActivityType): Promise<CardioSession[]> { const rows = activityType ? await db.getAllAsync<Row>('SELECT * FROM cardio_sessions WHERE date BETWEEN ? AND ? AND activity_type = ? ORDER BY date', [from, to, activityType]) : await db.getAllAsync<Row>('SELECT * FROM cardio_sessions WHERE date BETWEEN ? AND ? ORDER BY date', [from, to]); return rows.map(map); }
export async function getCardioSummaryByDateRange(db: SQLiteDatabase, from: string, to: string, activityType?: CardioActivityType): Promise<CardioSessionSummary> { return summarizeCardio(await getCardioSessionsByDateRange(db, from, to, activityType)); }
/** Creates a completed standalone cardio workout and its session atomically. */
export async function createStandaloneCardioWorkout(db: SQLiteDatabase, input: CardioSessionInput): Promise<string> { validateCardioInput(input); const workoutId = createId('workout'); const sessionId = createId('cardio'); const now = new Date().toISOString(); const started = new Date(new Date(input.date).getTime()).toISOString(); const completed = new Date(new Date(started).getTime() + input.durationSeconds * 1000).toISOString(); try { await db.withExclusiveTransactionAsync(async (transaction) => { await transaction.runAsync(`INSERT INTO workouts (id, name, workout_type, started_at, completed_at, duration_seconds, notes, status, created_at, updated_at) VALUES (?, ?, 'cardio', ?, ?, ?, ?, 'completed', ?, ?)`, [workoutId, input.activityType.replaceAll('_', ' '), started, completed, input.durationSeconds, input.notes, now, now]); const linked = { ...input, workoutId }; await transaction.runAsync(`INSERT INTO cardio_sessions (id, workout_id, workout_exercise_id, activity_type, date, duration_seconds, distance, calories, average_heart_rate, max_heart_rate, elevation_gain, average_pace_seconds_per_unit, average_speed, cadence, rounds, notes, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`, [...values(linked, sessionId, now)]); });const session=await getCardioSessionById(db,sessionId);if(session)await detectAndSaveCardioRecords(db,session);return workoutId; } catch (error) { throw toAppError(error, 'Could not save this cardio workout.'); } }
