import type { SQLiteDatabase } from 'expo-sqlite';
import { resetSettings } from './settingsRepository';

export interface DataSummary { totalExercises:number;customExercises:number;workoutPlans:number;completedWorkouts:number;activeWorkouts:number;workoutSets:number;cardioSessions:number;personalRecords:number;profiles:number;weightEntries:number;measurementEntries:number;measurementValues:number;earliestWorkout:string|null;latestWorkout:string|null;estimatedDatabaseBytes:number;lastBackupAt:string|null }
async function count(db:SQLiteDatabase,table:string,where=''):Promise<number>{return(await db.getFirstAsync<{count:number}>(`SELECT COUNT(*) count FROM ${table} ${where}`))?.count??0;}
export async function getDataSummary(db:SQLiteDatabase):Promise<DataSummary>{const [totalExercises,customExercises,workoutPlans,completedWorkouts,activeWorkouts,workoutSets,cardioSessions,personalRecords,profiles,weightEntries,measurementEntries,measurementValues,range,pages,last]=await Promise.all([count(db,'exercises'),count(db,'exercises','WHERE is_builtin=0'),count(db,'workout_plans'),count(db,'workouts',"WHERE status='completed'"),count(db,'workouts',"WHERE status='active'"),count(db,'workout_sets'),count(db,'cardio_sessions'),count(db,'personal_records'),count(db,'user_profile'),count(db,'body_weight_entries'),count(db,'body_measurement_entries'),count(db,'body_measurement_values'),db.getFirstAsync<{earliest:string|null;latest:string|null}>('SELECT MIN(started_at) earliest,MAX(started_at) latest FROM workouts'),db.getFirstAsync<{page_count:number;page_size:number}>('SELECT (SELECT page_count FROM pragma_page_count) page_count,(SELECT page_size FROM pragma_page_size) page_size'),db.getFirstAsync<{value:string}>('SELECT value FROM app_settings WHERE key=?',['preference.lastBackupAt'])]);return{totalExercises,customExercises,workoutPlans,completedWorkouts,activeWorkouts,workoutSets,cardioSessions,personalRecords,profiles,weightEntries,measurementEntries,measurementValues,earliestWorkout:range?.earliest??null,latestWorkout:range?.latest??null,estimatedDatabaseBytes:(pages?.page_count??0)*(pages?.page_size??0),lastBackupAt:last?.value?String(JSON.parse(last.value)):null};}
export async function deleteWorkoutHistory(db:SQLiteDatabase):Promise<void>{await db.withExclusiveTransactionAsync(async tx=>{await tx.runAsync("DELETE FROM workouts WHERE status='completed'");await tx.runAsync('DELETE FROM cardio_sessions WHERE workout_id IS NULL');});}
export async function deleteCustomExercises(db:SQLiteDatabase):Promise<void>{await db.withExclusiveTransactionAsync(async tx=>{await tx.runAsync(`UPDATE exercises SET is_archived=1,updated_at=? WHERE is_builtin=0 AND (EXISTS(SELECT 1 FROM workout_exercises we WHERE we.exercise_id=exercises.id) OR EXISTS(SELECT 1 FROM plan_exercises pe WHERE pe.exercise_id=exercises.id))`,[new Date().toISOString()]);await tx.runAsync(`DELETE FROM exercises WHERE is_builtin=0 AND NOT EXISTS(SELECT 1 FROM workout_exercises we WHERE we.exercise_id=exercises.id) AND NOT EXISTS(SELECT 1 FROM plan_exercises pe WHERE pe.exercise_id=exercises.id)`);});}
export async function deleteCustomPlans(db:SQLiteDatabase):Promise<void>{await db.runAsync('DELETE FROM workout_plans WHERE is_builtin=0');}
export async function resetUserData(db:SQLiteDatabase):Promise<void>{await db.withExclusiveTransactionAsync(async tx=>{await tx.runAsync('DELETE FROM user_profile');await tx.runAsync('UPDATE measurement_types SET is_active=1 WHERE is_builtin=1');await tx.runAsync('DELETE FROM workouts');await tx.runAsync('DELETE FROM cardio_sessions');await tx.runAsync('DELETE FROM workout_plans WHERE is_builtin=0');await tx.runAsync('DELETE FROM exercises WHERE is_builtin=0');await tx.runAsync('UPDATE workout_plans SET is_archived=0 WHERE is_builtin=1');await tx.runAsync('UPDATE exercises SET is_archived=0 WHERE is_builtin=1');await resetSettings(tx);});}
