import type { SQLiteDatabase } from 'expo-sqlite';
import { getExerciseById, listExercises } from './exerciseRepository';
import type { EquipmentProfile, ExerciseReplacementRelation, ExerciseRestriction, ReplacementRequest, ReplacementResult } from '@/types/exerciseReplacement';
import { createId } from '@/utils/ids';
import { AppError, toAppError } from '@/utils/errors';
import { weightModesCompatible } from '@/services/exerciseRecommendationService';

type RelationRow={id:string;source_exercise_id:string;replacement_exercise_id:string;relation_type:ExerciseReplacementRelation['relationType'];priority:number;equipment_context:string|null;difficulty_delta:number|null;built_in:number;active:number};
export async function getReplacementRelations(db:SQLiteDatabase,sourceExerciseId:string):Promise<ExerciseReplacementRelation[]>{return(await db.getAllAsync<RelationRow>('SELECT * FROM exercise_replacement_relations WHERE source_exercise_id=? AND active=1 ORDER BY priority DESC',[sourceExerciseId])).map(row=>({id:row.id,sourceExerciseId:row.source_exercise_id,replacementExerciseId:row.replacement_exercise_id,relationType:row.relation_type,priority:row.priority,equipmentContext:row.equipment_context,difficultyDelta:row.difficulty_delta,builtIn:row.built_in===1,active:row.active===1}));}
export async function getExerciseRestrictions(db:SQLiteDatabase):Promise<ExerciseRestriction[]>{const rows=await db.getAllAsync<{id:string;exercise_id:string;restriction_type:ExerciseRestriction['restrictionType'];reason:string|null;active:number;expires_at:string|null}>('SELECT id,exercise_id,restriction_type,reason,active,expires_at FROM exercise_restrictions WHERE active=1');return rows.map(row=>({id:row.id,exerciseId:row.exercise_id,restrictionType:row.restriction_type,reason:row.reason,active:row.active===1,expiresAt:row.expires_at}));}
export async function getDefaultEquipmentProfile(db:SQLiteDatabase):Promise<EquipmentProfile|null>{const row=await db.getFirstAsync<{id:string;name:string;default_profile:number;favorite:number;temporary:number;archived:number;last_used_at:string|null}>('SELECT * FROM equipment_profiles WHERE default_profile=1 AND archived=0 LIMIT 1');if(!row)return null;const items=await db.getAllAsync<{equipment_type:string}>('SELECT equipment_type FROM equipment_profile_items WHERE equipment_profile_id=? AND available=1',[row.id]);return{id:row.id,name:row.name,defaultProfile:true,favorite:row.favorite===1,temporary:row.temporary===1,archived:false,lastUsedAt:row.last_used_at,equipment:items.map(item=>item.equipment_type)};}
export async function getReplacementCandidates(db:SQLiteDatabase){return listExercises(db);}

/** Replaces only an active-session slot. Completed sets remain owned by the original exercise; only unfinished sets transfer. */
export async function replaceActiveSessionExercise(db:SQLiteDatabase,request:ReplacementRequest):Promise<ReplacementResult>{
  if(request.sourceContext!=='active_session'||request.scope!=='ACTIVE_SESSION'||!request.workoutExerciseId)throw new AppError('This replacement scope is not valid for the active workout.');
  const existing=await db.getFirstAsync<{id:string}>('SELECT id FROM exercise_replacement_audits WHERE operation_id=?',[request.operationId]);if(existing)return{auditId:existing.id,replacementWorkoutExerciseId:null,affectedCount:0,excludedCount:0,partial:false};
  const replacement=await getExerciseById(db,request.replacementExerciseId);if(!replacement||replacement.isArchived)throw new AppError('The replacement exercise is unavailable.');
  const original=await db.getFirstAsync<{id:string;workout_id:string;exercise_id:string;exercise_order:number;target_sets:number|null;target_reps_min:number|null;target_reps_max:number|null;target_weight:number|null;rest_seconds:number|null;notes:string|null;session_status:string}>('SELECT * FROM workout_exercises WHERE id=?',[request.workoutExerciseId]);
  if(!original)throw new AppError('The workout exercise no longer exists.');const workout=await db.getFirstAsync<{status:string}>('SELECT status FROM workouts WHERE id=?',[original.workout_id]);if(workout?.status!=='active')throw new AppError('Only the active workout can be changed here.');
  const source=await getExerciseById(db,original.exercise_id);if(!source)throw new AppError('The original exercise is unavailable.');
  const auditId=createId('replacement_audit');const replacementId=createId('workout_exercise');const now=new Date().toISOString();let partial=false;
  try{await db.withExclusiveTransactionAsync(async transaction=>{
    const completed=await transaction.getFirstAsync<{count:number}>('SELECT COUNT(*) AS count FROM workout_sets WHERE workout_exercise_id=? AND completed=1',[original.id]);partial=(completed?.count??0)>0;
    const unfinished=await transaction.getFirstAsync<{count:number}>('SELECT COUNT(*) AS count FROM workout_sets WHERE workout_exercise_id=? AND completed=0',[original.id]);
    const duplicate=await transaction.getFirstAsync<{id:string}>('SELECT id FROM workout_exercises WHERE workout_id=? AND exercise_id=? AND id<>? AND session_status<>\'removed\'',[original.workout_id,replacement.id,original.id]);if(duplicate)throw new AppError(`This workout already contains ${replacement.name}.`);
    const compatible=weightModesCompatible(source,replacement);const targetWeight=request.transferMode==='KEEP_SETS_REPS'&&compatible?original.target_weight:null;
    await transaction.runAsync('UPDATE workout_exercises SET replacement_status=?,replacement_audit_id=?,replacement_reason=?,replacement_transfer_mode=?,session_status=? WHERE id=?',[partial?'PARTIALLY_REPLACED':'REPLACED',auditId,request.reason,request.transferMode,partial?original.session_status:'removed',original.id]);
    if(partial)await transaction.runAsync('UPDATE workout_exercises SET exercise_order=exercise_order+1 WHERE workout_id=? AND exercise_order>?',[original.workout_id,original.exercise_order]);
    await transaction.runAsync(`INSERT INTO workout_exercises(id,workout_id,exercise_id,exercise_order,target_sets,target_reps_min,target_reps_max,target_weight,rest_seconds,notes,started_at,session_status,original_order,added_during_session,original_exercise_id,replacement_status,replacement_audit_id,replacement_reason,replacement_transfer_mode,original_exercise_snapshot_json,current_exercise_snapshot_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,'not_started',?,1,?,'REPLACED',?,?,?,?,?)`,[replacementId,original.workout_id,replacement.id,partial?original.exercise_order+1:original.exercise_order,partial?(unfinished?.count??0):original.target_sets,original.target_reps_min,original.target_reps_max,targetWeight,original.rest_seconds,original.notes,now,original.exercise_order,original.exercise_id,auditId,request.reason,request.transferMode,JSON.stringify(source),JSON.stringify(replacement)]);
    const sets=await transaction.getAllAsync<{id:string;set_number:number;weight:number|null;reps:number|null;set_type:string;rpe:number|null;notes:string|null;completed:number}>('SELECT id,set_number,weight,reps,set_type,rpe,notes,completed FROM workout_sets WHERE workout_exercise_id=? ORDER BY set_number',[original.id]);
    const movable=sets.filter(set=>set.completed===0);for(const [index,set]of movable.entries()){const weight=request.transferMode==='KEEP_SETS_REPS'&&compatible?set.weight:null;await transaction.runAsync(`INSERT INTO workout_sets(id,workout_exercise_id,set_number,weight,reps,set_type,rpe,completed,notes,created_at,updated_at,added_during_session,bar_profile_id,bar_snapshot_json,plate_combination_json) VALUES(?,?,?,?,?,?,?,0,?,?,?,1,NULL,NULL,NULL)`,[createId('workout_set'),replacementId,index+1,weight,set.reps,set.set_type,set.rpe,set.notes,now,now]);}
    await transaction.runAsync('DELETE FROM workout_sets WHERE workout_exercise_id=? AND completed=0',[original.id]);
    const memberships=await transaction.getAllAsync<{id:string;group_id:string;exercise_order:number}>('SELECT id,group_id,exercise_order FROM workout_group_exercises WHERE workout_exercise_id=?',[original.id]);for(const membership of memberships){if(partial){await transaction.runAsync('UPDATE workout_group_exercises SET exercise_order=exercise_order+1 WHERE group_id=? AND exercise_order>?',[membership.group_id,membership.exercise_order]);await transaction.runAsync('INSERT INTO workout_group_exercises(id,group_id,workout_exercise_id,exercise_order,created_at) VALUES(?,?,?,?,?)',[createId('workout_group_exercise'),membership.group_id,replacementId,membership.exercise_order+1,now]);}else await transaction.runAsync('UPDATE workout_group_exercises SET workout_exercise_id=? WHERE id=?',[replacementId,membership.id]);}
    await transaction.runAsync(`INSERT INTO exercise_replacement_audits(id,original_exercise_id,replacement_exercise_id,source_context,source_id,scope,reason,transfer_mode,session_id,affected_count,excluded_count,operation_id,created_at) VALUES(?,?,?,?,?,?,?,?,?,1,0,?,?)`,[auditId,source.id,replacement.id,request.sourceContext,request.sourceId,request.scope,request.reason,request.transferMode,original.workout_id,request.operationId,now]);
    await transaction.runAsync('UPDATE workouts SET current_exercise_id=?,updated_at=? WHERE id=?',[replacementId,now,original.workout_id]);
  });return{auditId,replacementWorkoutExerciseId:replacementId,affectedCount:1,excludedCount:0,partial};}catch(error){throw toAppError(error,'Could not replace this exercise.');}
}
