import type { SQLiteDatabase } from 'expo-sqlite';
import type { BarProfile, PlateCalculationMode, PlateInventoryItem, PlateInventoryProfile, PlateLoadResult, PlateUnit } from '@/types/plateCalculator';
import { AppError } from '@/utils/errors'; import { createId } from '@/utils/ids'; import { displayToKilograms } from '@/utils/units';
interface BarRow{id:string;name:string;bar_type:string;weight:number;unit:PlateUnit;default_collar_weight:number;variable_weight:number;fixed_weight:number;is_favorite:number;is_builtin:number;is_archived:number;notes:string|null}
interface ItemRow{id:string;plate_weight:number;unit:PlateUnit;quantity:number;enabled:number;display_order:number;custom:number}
interface ProfileRow{id:string;name:string;unit:PlateUnit;default_bar_id:string|null;default_collar_weight:number}
export async function getBarProfiles(db:SQLiteDatabase,unit:PlateUnit):Promise<BarProfile[]>{return(await db.getAllAsync<BarRow>('SELECT * FROM bar_profiles WHERE unit=? AND is_archived=0 ORDER BY is_favorite DESC,is_builtin DESC,weight DESC',[unit])).map(r=>({id:r.id,name:r.name,barType:r.bar_type,weight:r.weight,unit:r.unit,defaultCollarWeight:r.default_collar_weight,variableWeight:r.variable_weight===1,fixedWeight:r.fixed_weight===1,isFavorite:r.is_favorite===1,isBuiltin:r.is_builtin===1,isArchived:r.is_archived===1,notes:r.notes}))}
export async function getInventoryProfiles(db:SQLiteDatabase,unit:PlateUnit):Promise<PlateInventoryProfile[]>{const profiles=await db.getAllAsync<ProfileRow>('SELECT * FROM plate_inventory_profiles WHERE unit=? AND is_archived=0 ORDER BY is_favorite DESC,is_builtin DESC',[unit]);return Promise.all(profiles.map(async p=>({id:p.id,name:p.name,unit:p.unit,defaultBarId:p.default_bar_id,defaultCollarWeight:p.default_collar_weight,items:(await db.getAllAsync<ItemRow>('SELECT * FROM plate_inventory_items WHERE inventory_profile_id=? ORDER BY display_order',[p.id])).map((x):PlateInventoryItem=>({id:x.id,plateWeight:x.plate_weight,unit:x.unit,quantity:x.quantity,enabled:x.enabled===1,displayOrder:x.display_order,custom:x.custom===1}))})))}
/** Applies canonical kg plus a full equipment snapshot atomically; the set remains incomplete. */
export async function applyPlateLoadToSet(db:SQLiteDatabase,setId:string,bar:BarProfile,profile:PlateInventoryProfile,result:PlateLoadResult,collarWeight:number,mode:PlateCalculationMode):Promise<void>{const now=new Date().toISOString();const kg=displayToKilograms(result.loadedWeight,bar.unit);await db.withExclusiveTransactionAsync(async tx=>{const found=await tx.getFirstAsync('SELECT id FROM workout_sets WHERE id=?',[setId]);if(!found)throw new AppError('The selected set no longer exists.');await tx.runAsync(`UPDATE workout_sets SET weight=?,bar_profile_id=?,bar_snapshot_json=?,collar_weight=?,plate_inventory_profile_id=?,plate_combination_json=?,calculated_target_weight=?,loaded_total_weight=?,plate_calculation_mode=?,plate_calculation_exact=?,plate_calculation_difference=?,updated_at=? WHERE id=?`,[kg,bar.id,JSON.stringify(bar),collarWeight,profile.id,JSON.stringify(result.platesPerSide),result.targetWeight,result.loadedWeight,mode,result.exact?1:0,result.difference,now,setId]);await tx.runAsync(`INSERT INTO plate_calculation_history(id,source_type,source_id,target_weight,loaded_weight,difference,unit,bar_snapshot_json,inventory_profile_id,plate_combination_json,exact,calculation_mode,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)`,[createId('plate_history'),'active_set',setId,result.targetWeight,result.loadedWeight,result.difference,bar.unit,JSON.stringify(bar),profile.id,JSON.stringify(result.platesPerSide),result.exact?1:0,mode,now]);});}
