import type { SQLiteDatabase } from 'expo-sqlite'; import { groupTypeAfterAddition, groupTypeAfterRemoval, validateGroupSize } from '../services/advancedSetService'; import type { CreateWorkoutGroupInput, WorkoutGroup, WorkoutGroupExercise, WorkoutGroupType } from '@/types/workoutGroup'; import { AppError, toAppError } from '../utils/errors'; import { createId } from '../utils/ids';
interface GroupRow { id: string; workout_id: string; group_type: WorkoutGroupType; name: string | null; group_order: number; target_rounds: number | null; completed_rounds: number; rest_between_exercises_seconds: number | null; rest_between_rounds_seconds: number | null; notes: string | null; created_at: string; updated_at: string; }
interface MemberRow { id: string; group_id: string; workout_exercise_id: string; exercise_order: number; created_at: string; exercise_name: string; }
const member = (row: MemberRow): WorkoutGroupExercise => ({ id: row.id, groupId: row.group_id, workoutExerciseId: row.workout_exercise_id, exerciseOrder: row.exercise_order, createdAt: row.created_at, exerciseName: row.exercise_name });
async function hydrate(db: SQLiteDatabase, row: GroupRow): Promise<WorkoutGroup> { const members = await db.getAllAsync<MemberRow>(`SELECT wge.*, e.name AS exercise_name FROM workout_group_exercises wge JOIN workout_exercises we ON we.id=wge.workout_exercise_id JOIN exercises e ON e.id=we.exercise_id WHERE wge.group_id=? ORDER BY wge.exercise_order`, [row.id]); return { id: row.id, workoutId: row.workout_id, groupType: row.group_type, name: row.name, groupOrder: row.group_order, targetRounds: row.target_rounds, completedRounds: row.completed_rounds, restBetweenExercisesSeconds: row.rest_between_exercises_seconds, restBetweenRoundsSeconds: row.rest_between_rounds_seconds, notes: row.notes, createdAt: row.created_at, updatedAt: row.updated_at, exercises: members.map(member) }; }
export async function createWorkoutGroup(db: SQLiteDatabase, input: CreateWorkoutGroupInput): Promise<string> { validateGroupSize(input.groupType, input.workoutExerciseIds.length); if (new Set(input.workoutExerciseIds).size !== input.workoutExerciseIds.length) throw new AppError('An exercise cannot appear twice in the same group.'); if (input.targetRounds < 1) throw new AppError('Rounds must be at least one.'); const id=createId('workout_group'); const now=new Date().toISOString(); try { await db.withExclusiveTransactionAsync(async (tx)=>{ const order=await tx.getFirstAsync<{next:number}>('SELECT COALESCE(MAX(group_order),-1)+1 AS next FROM workout_groups WHERE workout_id=?',[input.workoutId]); await tx.runAsync(`INSERT INTO workout_groups (id,workout_id,group_type,name,group_order,target_rounds,rest_between_exercises_seconds,rest_between_rounds_seconds,notes,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)`,[id,input.workoutId,input.groupType,input.name,order?.next??0,input.targetRounds,input.restBetweenExercisesSeconds,input.restBetweenRoundsSeconds,input.notes,now,now]); for(const [index,workoutExerciseId] of input.workoutExerciseIds.entries()) await tx.runAsync('INSERT INTO workout_group_exercises (id,group_id,workout_exercise_id,exercise_order,created_at) VALUES (?,?,?,?,?)',[createId('group_exercise'),id,workoutExerciseId,index,now]); }); return id; } catch(error){ throw toAppError(error,'Could not create this workout group.'); } }
export async function getGroupsForWorkout(db:SQLiteDatabase,workoutId:string):Promise<WorkoutGroup[]>{ const rows=await db.getAllAsync<GroupRow>('SELECT * FROM workout_groups WHERE workout_id=? ORDER BY group_order',[workoutId]); return Promise.all(rows.map((row)=>hydrate(db,row))); }
export async function getGroupWithExercises(db:SQLiteDatabase,id:string):Promise<WorkoutGroup|null>{const row=await db.getFirstAsync<GroupRow>('SELECT * FROM workout_groups WHERE id=?',[id]);return row?hydrate(db,row):null;}
export async function updateWorkoutGroup(db:SQLiteDatabase,id:string,patch:{name:string|null;targetRounds:number;restBetweenExercisesSeconds:number;restBetweenRoundsSeconds:number;notes:string|null}):Promise<void>{if(patch.targetRounds<1)throw new AppError('Rounds must be at least one.');await db.runAsync('UPDATE workout_groups SET name=?,target_rounds=?,rest_between_exercises_seconds=?,rest_between_rounds_seconds=?,notes=?,updated_at=? WHERE id=?',[patch.name,patch.targetRounds,patch.restBetweenExercisesSeconds,patch.restBetweenRoundsSeconds,patch.notes,new Date().toISOString(),id]);}
/** Membership rows cascade, while workout exercises remain because the group never owns them. */
export async function deleteWorkoutGroup(db:SQLiteDatabase,id:string):Promise<void>{await db.withExclusiveTransactionAsync(async(tx)=>{await tx.runAsync('DELETE FROM workout_groups WHERE id=?',[id]);});}
export async function addExerciseToGroup(db:SQLiteDatabase,groupId:string,workoutExerciseId:string):Promise<void>{await db.withExclusiveTransactionAsync(async(tx)=>{const group=await tx.getFirstAsync<{group_type:WorkoutGroupType}>('SELECT group_type FROM workout_groups WHERE id=?',[groupId]);if(!group)throw new AppError('Workout group not found.');const count=await tx.getFirstAsync<{count:number}>('SELECT COUNT(*) AS count FROM workout_group_exercises WHERE group_id=?',[groupId]);const next=(count?.count??0);const type=groupTypeAfterAddition(group.group_type,next+1);await tx.runAsync('INSERT INTO workout_group_exercises (id,group_id,workout_exercise_id,exercise_order,created_at) VALUES (?,?,?,?,?)',[createId('group_exercise'),groupId,workoutExerciseId,next,new Date().toISOString()]);if(type!==group.group_type)await tx.runAsync('UPDATE workout_groups SET group_type=?,updated_at=? WHERE id=?',[type,new Date().toISOString(),groupId]);});}
export async function removeExerciseFromGroup(db:SQLiteDatabase,groupId:string,workoutExerciseId:string):Promise<void>{await db.withExclusiveTransactionAsync(async(tx)=>{const group=await tx.getFirstAsync<{group_type:WorkoutGroupType}>('SELECT group_type FROM workout_groups WHERE id=?',[groupId]);if(!group)return;await tx.runAsync('DELETE FROM workout_group_exercises WHERE group_id=? AND workout_exercise_id=?',[groupId,workoutExerciseId]);const rows=await tx.getAllAsync<{id:string}>('SELECT id FROM workout_group_exercises WHERE group_id=? ORDER BY exercise_order',[groupId]);const type=groupTypeAfterRemoval(group.group_type,rows.length);if(!type){await tx.runAsync('DELETE FROM workout_groups WHERE id=?',[groupId]);return;}for(const[index,row]of rows.entries())await tx.runAsync('UPDATE workout_group_exercises SET exercise_order=? WHERE id=?',[index,row.id]);await tx.runAsync('UPDATE workout_groups SET group_type=?,updated_at=? WHERE id=?',[type,new Date().toISOString(),groupId]);});}
export async function reorderGroupExercises(db:SQLiteDatabase,groupId:string,ids:string[]):Promise<void>{await db.withExclusiveTransactionAsync(async(tx)=>{for(const[index,id]of ids.entries())await tx.runAsync('UPDATE workout_group_exercises SET exercise_order=? WHERE id=? AND group_id=?',[index,id,groupId]);});}
export async function updateCompletedRounds(db:SQLiteDatabase,id:string,rounds:number):Promise<void>{if(rounds<0)throw new AppError('Completed rounds cannot be negative.');await db.runAsync('UPDATE workout_groups SET completed_rounds=?,updated_at=? WHERE id=?',[rounds,new Date().toISOString(),id]);}
