import { zodResolver } from '@hookform/resolvers/zod';
import { Controller, useForm } from 'react-hook-form';
import { StyleSheet, Text, View } from 'react-native';
import { z } from 'zod';
import { colors } from '@/constants/colors'; import { spacing } from '@/constants/spacing'; import { typography } from '@/constants/typography'; import { milesToKilometers } from '@/services/cardioService'; import type { CardioActivityType, CardioSessionInput } from '@/types/cardio';
import { AppButton } from './AppButton'; import { AppInput } from './AppInput'; import { CardioActivityPicker } from './CardioActivityPicker'; import { CardioTimer } from './CardioTimer'; import { FilterChip } from './FilterChip';

const nonnegative = (label: string) => z.string().refine((value) => value === '' || (Number.isFinite(Number(value)) && Number(value) >= 0), `${label} cannot be negative`);
const schema = z.object({ activityType: z.string(), date: z.string().min(1), durationMinutes: z.string().refine((value) => Number(value) > 0, 'Duration must be greater than zero'), distance: nonnegative('Distance'), distanceUnit: z.enum(['km', 'mi']), averageHeartRate: nonnegative('Heart rate'), maxHeartRate: nonnegative('Heart rate'), calories: nonnegative('Calories'), elevationGain: nonnegative('Elevation'), cadence: nonnegative('Cadence'), notes: z.string() });
type Form = z.infer<typeof schema>; const optional = (value: string) => value === '' ? null : Number(value);

export function CardioSessionForm({ onSubmit, loading = false }: { onSubmit: (input: CardioSessionInput) => Promise<void>; loading?: boolean }) {
  const { control, handleSubmit, setValue, watch, formState: { errors } } = useForm<Form>({ resolver: zodResolver(schema), defaultValues: { activityType: 'running', date: new Date().toISOString(), durationMinutes: '', distance: '', distanceUnit: 'km', averageHeartRate: '', maxHeartRate: '', calories: '', elevationGain: '', cadence: '', notes: '' } }); const unit = watch('distanceUnit');
  const submit = handleSubmit(async (value) => { const distance = optional(value.distance); await onSubmit({ workoutId: null, workoutExerciseId: null, activityType: value.activityType as CardioActivityType, date: value.date, durationSeconds: Math.round(Number(value.durationMinutes) * 60), distanceKm: distance === null ? null : unit === 'mi' ? milesToKilometers(distance) : distance, averageHeartRate: optional(value.averageHeartRate), maxHeartRate: optional(value.maxHeartRate), calories: optional(value.calories), elevationGain: optional(value.elevationGain), cadence: optional(value.cadence), rounds: null, notes: value.notes.trim() || null }); });
  return <View style={styles.form}><Text style={styles.label}>Activity</Text><Controller control={control} name="activityType" render={({ field }) => <CardioActivityPicker value={field.value as CardioActivityType} onChange={field.onChange} />} /><CardioTimer onElapsed={(seconds) => setValue('durationMinutes', (seconds / 60).toFixed(2))} /><Controller control={control} name="date" render={({ field }) => <AppInput label="Start date/time (ISO)" value={field.value} onChangeText={field.onChange} error={errors.date?.message} />} /><Controller control={control} name="durationMinutes" render={({ field }) => <AppInput label="Duration minutes" keyboardType="decimal-pad" value={field.value} onChangeText={field.onChange} error={errors.durationMinutes?.message} />} /><View style={styles.row}><Controller control={control} name="distance" render={({ field }) => <AppInput containerStyle={styles.flex} label="Distance" keyboardType="decimal-pad" value={field.value} onChangeText={field.onChange} error={errors.distance?.message} />} /><View style={styles.unit}><FilterChip label="km" selected={unit === 'km'} onPress={() => setValue('distanceUnit', 'km')} /><FilterChip label="mi" selected={unit === 'mi'} onPress={() => setValue('distanceUnit', 'mi')} /></View></View><View style={styles.row}><Controller control={control} name="averageHeartRate" render={({ field }) => <AppInput containerStyle={styles.flex} label="Average HR" keyboardType="number-pad" value={field.value} onChangeText={field.onChange} />} /><Controller control={control} name="maxHeartRate" render={({ field }) => <AppInput containerStyle={styles.flex} label="Maximum HR" keyboardType="number-pad" value={field.value} onChangeText={field.onChange} />} /></View><View style={styles.row}><Controller control={control} name="calories" render={({ field }) => <AppInput containerStyle={styles.flex} label="Calories" keyboardType="number-pad" value={field.value} onChangeText={field.onChange} />} /><Controller control={control} name="elevationGain" render={({ field }) => <AppInput containerStyle={styles.flex} label="Elevation gain" keyboardType="decimal-pad" value={field.value} onChangeText={field.onChange} />} /></View><Controller control={control} name="cadence" render={({ field }) => <AppInput label="Cadence" keyboardType="number-pad" value={field.value} onChangeText={field.onChange} />} /><Controller control={control} name="notes" render={({ field }) => <AppInput label="Notes" multiline value={field.value} onChangeText={field.onChange} />} /><AppButton label="Save Cardio Workout" loading={loading} onPress={() => void submit()} /></View>;
}
const styles = StyleSheet.create({ form: { gap: spacing.md }, label: { ...typography.label, color: colors.text }, row: { flexDirection: 'row', gap: spacing.sm }, flex: { flex: 1 }, unit: { justifyContent: 'flex-end', flexDirection: 'row', gap: spacing.xs } });
