import { useEffect, useState } from 'react';
import { Modal, Pressable, StyleSheet, Text, View } from 'react-native';
import { AppButton } from './AppButton';
import { AppInput } from './AppInput';
import { useAppColors } from '@/hooks/useAppColors';
import { radius, spacing } from '@/constants/spacing';
import { typography } from '@/constants/typography';

const months=['January','February','March','April','May','June','July','August','September','October','November','December'];
export function PlannerMonthYearPicker({visible,value,onClose,onSelect}:{visible:boolean;value:Date;onClose:()=>void;onSelect:(date:Date)=>void}){const colors=useAppColors();const[year,setYear]=useState(String(value.getFullYear()));useEffect(()=>{if(visible)setYear(String(value.getFullYear()));},[value,visible]);const parsed=Math.min(2200,Math.max(1900,Number(year)||value.getFullYear()));const choose=(month:number)=>{onSelect(new Date(parsed,month,1,12));onClose();};return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}><Pressable accessibilityRole="button" accessibilityLabel="Close month and year picker" style={[styles.overlay,{backgroundColor:colors.overlay}]} onPress={onClose}><Pressable style={[styles.sheet,{backgroundColor:colors.surface,borderColor:colors.border}]} onPress={event=>event.stopPropagation()}><View style={styles.head}><View><Text style={[styles.eyebrow,{color:colors.accent}]}>JUMP TO DATE</Text><Text accessibilityRole="header" style={[styles.title,{color:colors.text}]}>Choose month & year</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Close" hitSlop={12} onPress={onClose}><Text style={[styles.close,{color:colors.textMuted}]}>×</Text></Pressable></View><View style={styles.yearRow}><Pressable accessibilityRole="button" accessibilityLabel="Previous year" style={[styles.yearButton,{borderColor:colors.border}]} onPress={()=>setYear(String(parsed-1))}><Text style={[styles.arrow,{color:colors.text}]}>‹</Text></Pressable><AppInput containerStyle={styles.yearInput} label="Year" keyboardType="number-pad" maxLength={4} value={year} onChangeText={setYear}/><Pressable accessibilityRole="button" accessibilityLabel="Next year" style={[styles.yearButton,{borderColor:colors.border}]} onPress={()=>setYear(String(parsed+1))}><Text style={[styles.arrow,{color:colors.text}]}>›</Text></Pressable></View><View style={styles.grid}>{months.map((month,index)=>{const selected=index===value.getMonth()&&parsed===value.getFullYear();return <Pressable key={month} accessibilityRole="button" accessibilityLabel={`${month} ${parsed}`} accessibilityState={{selected}} onPress={()=>choose(index)} style={[styles.month,{borderColor:selected?colors.accent:colors.border,backgroundColor:selected?colors.accent:colors.surfaceElevated}]}><Text style={[styles.monthText,{color:selected?colors.accentText:colors.text}]}>{month.slice(0,3)}</Text></Pressable>})}</View><AppButton label="Go to Today" variant="secondary" onPress={()=>{onSelect(new Date());onClose();}}/></Pressable></Pressable></Modal>}
const styles=StyleSheet.create({overlay:{flex:1,justifyContent:'center',padding:spacing.lg},sheet:{borderRadius:24,borderWidth:1,padding:spacing.xl,gap:spacing.lg},head:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start'},eyebrow:{...typography.caption,fontWeight:'800',letterSpacing:1.2},title:{...typography.title},close:{fontSize:32,lineHeight:32},yearRow:{flexDirection:'row',alignItems:'flex-end',gap:spacing.sm},yearButton:{width:52,height:52,borderWidth:1,borderRadius:radius.md,alignItems:'center',justifyContent:'center'},arrow:{fontSize:30},yearInput:{flex:1},grid:{flexDirection:'row',flexWrap:'wrap',gap:spacing.sm},month:{width:'22.8%',minHeight:52,borderWidth:1,borderRadius:radius.md,alignItems:'center',justifyContent:'center'},monthText:{...typography.label},yearGo:{marginTop:spacing.sm}});
