import { Ionicons } from '@expo/vector-icons';
import { addDays, format, isSameDay, isSameMonth } from 'date-fns';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import type { ScheduledWorkout } from '@/types/scheduledWorkout';
import type { FirstDayOfWeek } from '@/types/settings';
import { useAppColors } from '@/hooks/useAppColors';
import { spacing } from '@/constants/spacing';
import { plannerGridRange } from '@/services/scheduledWorkoutService';

const icon=(type:string):keyof typeof Ionicons.glyphMap=>type==='running'||type==='walking'?'walk':type==='cycling'?'bicycle':type==='yoga'||type==='mobility'?'body':type==='cardio'||type==='swimming'?'heart':'barbell';
export function TrainingMonthPlanner({month,selectedDate,items,firstDayOfWeek,onSelectDate}:{month:Date;selectedDate:string;items:ScheduledWorkout[];firstDayOfWeek:FirstDayOfWeek;onSelectDate:(date:string)=>void}){const colors=useAppColors();const range=plannerGridRange(month,firstDayOfWeek);const days:Date[]=[];for(let day=range.from;day<=range.to;day=addDays(day,1))days.push(day);const labels=firstDayOfWeek===1?['Mon','Tue','Wed','Thu','Fri','Sat','Sun']:['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];return <View style={[styles.shell,{backgroundColor:colors.surface,borderColor:colors.border}]}><View style={styles.week}>{labels.map(label=><Text key={label} style={[styles.weekLabel,{color:colors.textMuted}]}>{label}</Text>)}</View><View style={styles.grid}>{days.map(day=>{const key=format(day,'yyyy-MM-dd');const dayItems=items.filter(item=>item.scheduledDate===key);const selected=key===selectedDate;const today=isSameDay(day,new Date());const outside=!isSameMonth(day,month);return <Pressable key={key} accessibilityRole="button" accessibilityLabel={`${format(day,'EEEE, MMMM d')}. ${dayItems.length} workouts planned`} accessibilityState={{selected}} onPress={()=>onSelectDate(key)} style={[styles.cell,{borderColor:colors.border,backgroundColor:selected?colors.surfaceElevated:'transparent'},selected&&{borderColor:colors.accent},outside&&styles.outside]}><View style={styles.dayHead}><Text style={[styles.dayNumber,{color:outside?colors.textMuted:colors.text},today&&{backgroundColor:colors.accent,color:colors.accentText}]}>{format(day,'d')}</Text>{dayItems.length>0?<Text style={[styles.count,{color:colors.textMuted}]}>{dayItems.length}</Text>:null}</View>{dayItems.slice(0,2).map(item=><View key={item.id} style={[styles.event,{backgroundColor:item.status==='completed'?colors.success:item.status==='skipped'?colors.warning:colors.accent}]}><Ionicons name={icon(item.snapshotWorkoutType)} size={10} color={item.status==='skipped'?colors.accentText:colors.accentText}/><Text numberOfLines={1} style={[styles.eventText,{color:colors.accentText}]}>{item.snapshotName}</Text></View>)}{dayItems.length>2?<Text style={[styles.more,{color:colors.textMuted}]}>+{dayItems.length-2} more</Text>:null}</Pressable>})}</View></View>}
const styles=StyleSheet.create({shell:{marginHorizontal:spacing.lg,borderWidth:1,borderRadius:22,overflow:'hidden'},week:{flexDirection:'row',paddingHorizontal:4,paddingTop:spacing.md,paddingBottom:spacing.sm},weekLabel:{width:'14.285%',textAlign:'center',fontSize:11,fontWeight:'700'},grid:{flexDirection:'row',flexWrap:'wrap'},cell:{width:'14.285%',minHeight:78,borderTopWidth:StyleSheet.hairlineWidth,borderRightWidth:StyleSheet.hairlineWidth,padding:4,gap:3},outside:{opacity:.42},dayHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},dayNumber:{fontSize:12,fontWeight:'700',width:24,height:24,lineHeight:24,textAlign:'center',borderRadius:12},count:{fontSize:9},event:{minHeight:17,borderRadius:5,paddingHorizontal:3,flexDirection:'row',alignItems:'center',gap:2},eventText:{fontSize:8,fontWeight:'800',flex:1},more:{fontSize:8,fontWeight:'700'}});
