import { useCallback, useEffect, useState } from 'react'; import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native'; import { router } from 'expo-router';
import { AppInput } from './AppInput'; import { FilterChip } from './FilterChip'; import { colors } from '@/constants/colors'; import { radius, spacing } from '@/constants/spacing'; import { typography } from '@/constants/typography'; import { setTypes, type SetType, type WorkoutSet, type WorkoutSetUpdate } from '@/types/workout';
const numeric = (value: string): number | null => value.trim() === '' ? null : Number.isFinite(Number(value)) ? Number(value) : null;
export function WorkoutSetRow({ set, previous, onSave, onDelete, onComplete, registerFlush }: { set: WorkoutSet; previous?: WorkoutSet; onSave: (value: WorkoutSetUpdate) => Promise<void>; onDelete: () => void; onComplete: (completed: boolean) => void; registerFlush?: (setId: string, flush: () => Promise<void>) => () => void }) {
  const [weight, setWeight] = useState(set.weight?.toString() ?? ''); const [reps, setReps] = useState(set.reps?.toString() ?? ''); const [rpe, setRpe] = useState(set.rpe?.toString() ?? ''); const [notes, setNotes] = useState(set.notes ?? ''); const [type, setType] = useState<SetType>(set.setType); const [completed, setCompleted] = useState(set.completed);
  const [duration,setDuration]=useState(set.durationSeconds?.toString()??'');const[distance,setDistance]=useState(set.distance?.toString()??'');const[assistance,setAssistance]=useState(set.assistanceWeight?.toString()??'');const[bodyweight,setBodyweight]=useState(set.bodyweightValue?.toString()??'');const[added,setAdded]=useState(set.addedWeight?.toString()??'');
  useEffect(() => { setCompleted(set.completed); }, [set.completed]);
  const value = useCallback((override?: Partial<WorkoutSetUpdate>): WorkoutSetUpdate => ({ weight: numeric(weight), reps: numeric(reps), durationSeconds:numeric(duration),distance:numeric(distance),assistanceWeight:numeric(assistance),bodyweightValue:numeric(bodyweight),addedWeight:numeric(added),isAmrap:type==='amrap',rpe: numeric(rpe), notes: notes || null, setType: type, completed, ...override }), [added, assistance, bodyweight, completed, distance, duration, notes, reps, rpe, type, weight]);
  const save = useCallback((override?: Partial<WorkoutSetUpdate>) => onSave(value(override)), [onSave, value]);
  useEffect(() => registerFlush?.(set.id, () => save()), [registerFlush, save, set.id]);
  const toggle = () => {
    const next = !completed; const parsedReps = numeric(reps); const parsedWeight = numeric(weight); const parsedRpe = numeric(rpe);
    if(next&&type==='timed'&&(!numeric(duration)||numeric(duration)!<=0)){Alert.alert('Duration required','Enter a positive duration.');return;}
    if(next&&type==='distance'&&(!numeric(distance)||numeric(distance)!<=0)){Alert.alert('Distance required','Enter a positive distance.');return;}
    if (next && !['timed','distance'].includes(type) && (!parsedReps || parsedReps <= 0)) { Alert.alert('Repetitions required', 'Enter at least one repetition before completing this set.'); return; }
    if (next && parsedWeight !== null && parsedWeight < 0) { Alert.alert('Invalid weight', 'Weight cannot be negative.'); return; }
    if (next && parsedRpe !== null && (parsedRpe < 0 || parsedRpe > 10)) { Alert.alert('Invalid RPE', 'RPE must be between 0 and 10.'); return; }
    setCompleted(next); void save({ completed: next }); onComplete(next);
  };
  const copyPrevious = () => { if (!previous) return; setWeight(previous.weight?.toString() ?? ''); setReps(previous.reps?.toString() ?? ''); setRpe(previous.rpe?.toString() ?? ''); setType(previous.setType); void onSave({ weight: previous.weight, reps: previous.reps, rpe: previous.rpe, setType: previous.setType, completed, notes: notes || null }); };
  return <View style={[styles.card, completed && styles.complete]} accessibilityLabel={`Set ${set.setNumber}, ${completed ? 'completed' : 'not completed'}`}><View style={styles.head}><Text style={styles.number}>Set {set.setNumber}{completed ? ' · Completed' : ''}</Text><View style={styles.headActions}>{previous ? <Pressable accessibilityRole="button" accessibilityLabel={`Copy values into set ${set.setNumber}`} hitSlop={8} onPress={copyPrevious}><Text style={styles.copy}>Copy previous</Text></Pressable> : null}<Pressable accessibilityRole="button" accessibilityLabel={`Delete set ${set.setNumber}`} hitSlop={8} onPress={onDelete}><Text style={styles.delete}>Delete</Text></Pressable><Pressable accessibilityRole="checkbox" accessibilityLabel={`Set ${set.setNumber} completed`} accessibilityState={{ checked: completed }} hitSlop={6} onPress={toggle} style={[styles.check, completed && styles.checked]}><Text style={styles.checkText}>{completed ? '✓' : ''}</Text></Pressable></View></View>
    <View style={styles.inputs}><AppInput containerStyle={styles.flex} label="Weight" keyboardType="decimal-pad" value={weight} onChangeText={setWeight} onBlur={() => void save()} /><AppInput containerStyle={styles.flex} label="Reps" keyboardType="number-pad" value={reps} onChangeText={setReps} onBlur={() => void save()} /><AppInput containerStyle={styles.flex} label="RPE" keyboardType="decimal-pad" value={rpe} onChangeText={setRpe} onBlur={() => void save()} /></View><Pressable accessibilityRole="button" accessibilityLabel={`Open plate calculator for set ${set.setNumber}`} onPress={()=>router.push({pathname:'/tools/plate-calculator',params:{setId:set.id}})} style={{minHeight:44,alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:colors.border,borderRadius:radius.sm}}><Text style={styles.copy}>Calculate bar plates</Text></Pressable>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.types}>{setTypes.map((item) => <FilterChip key={item} label={item} selected={type === item} onPress={() => { setType(item); void save({ setType: item }); }} />)}</ScrollView>
    {type==='timed'||type==='amrap'?<AppInput label="Duration seconds" keyboardType="number-pad" value={duration} onChangeText={setDuration} onBlur={()=>void save()}/>:null}{type==='distance'||type==='timed'?<AppInput label="Distance km (optional for timed)" keyboardType="decimal-pad" value={distance} onChangeText={setDistance} onBlur={()=>void save()}/>:null}{type==='assisted'?<AppInput label="Assistance weight kg" keyboardType="decimal-pad" value={assistance} onChangeText={setAssistance} onBlur={()=>void save()}/>:null}{type==='bodyweight'?<View style={styles.inputs}><AppInput containerStyle={styles.flex} label="Bodyweight kg" keyboardType="decimal-pad" value={bodyweight} onChangeText={setBodyweight} onBlur={()=>void save()}/><AppInput containerStyle={styles.flex} label="Added kg" keyboardType="decimal-pad" value={added} onChangeText={setAdded} onBlur={()=>void save()}/><AppInput containerStyle={styles.flex} label="Assistance kg" keyboardType="decimal-pad" value={assistance} onChangeText={setAssistance} onBlur={()=>void save()}/></View>:null}
    <AppInput label="Set notes" value={notes} onChangeText={setNotes} onBlur={() => void save()} />
  </View>;
}
const styles = StyleSheet.create({ card: { padding: spacing.md, borderRadius: radius.md, backgroundColor: colors.surfaceElevated, borderWidth: 1, borderColor: colors.border, gap: spacing.md }, complete: { borderColor: colors.accent, backgroundColor: '#10291B' }, head: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, number: { ...typography.label, color: colors.text }, headActions: { flexDirection: 'row', alignItems: 'center', gap: spacing.md }, copy: { ...typography.caption, color: colors.accent }, delete: { ...typography.caption, color: colors.danger }, check: { width: 34, height: 34, borderRadius: 17, borderWidth: 2, borderColor: colors.textMuted, alignItems: 'center', justifyContent: 'center' }, checked: { backgroundColor: colors.accent, borderColor: colors.accent }, checkText: { color: colors.accentText, fontWeight: '900' }, inputs: { flexDirection: 'row', gap: spacing.sm }, flex: { flex: 1 }, types: { gap: spacing.sm } });
