import { useEffect, useState } from 'react'; import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { AppInput } from './AppInput'; import { FilterChip } from './FilterChip'; import { colors } from '@/constants/colors'; import { radius, spacing } from '@/constants/spacing'; import { typography } from '@/constants/typography'; import { setTypes, type SetType, type WorkoutSet, type WorkoutSetUpdate } from '@/types/workout';
const numeric = (value: string): number | null => value.trim() === '' ? null : Number.isFinite(Number(value)) ? Number(value) : null;
export function WorkoutSetRow({ set, previous, onSave, onDelete, onComplete }: { set: WorkoutSet; previous?: WorkoutSet; onSave: (value: WorkoutSetUpdate) => Promise<void>; onDelete: () => void; onComplete: (completed: boolean) => void }) {
  const [weight, setWeight] = useState(set.weight?.toString() ?? ''); const [reps, setReps] = useState(set.reps?.toString() ?? ''); const [rpe, setRpe] = useState(set.rpe?.toString() ?? ''); const [notes, setNotes] = useState(set.notes ?? ''); const [type, setType] = useState<SetType>(set.setType); const [completed, setCompleted] = useState(set.completed);
  useEffect(() => { setCompleted(set.completed); }, [set.completed]);
  const value = (override?: Partial<WorkoutSetUpdate>): WorkoutSetUpdate => ({ weight: numeric(weight), reps: numeric(reps), rpe: numeric(rpe), notes: notes || null, setType: type, completed, ...override });
  const save = (override?: Partial<WorkoutSetUpdate>) => onSave(value(override)); const toggle = () => {
    const next = !completed; const parsedReps = numeric(reps); const parsedWeight = numeric(weight); const parsedRpe = numeric(rpe);
    if (next && (!parsedReps || parsedReps <= 0)) { Alert.alert('Repetitions required', 'Enter at least one repetition before completing this set.'); return; }
    if (next && parsedWeight !== null && parsedWeight < 0) { Alert.alert('Invalid weight', 'Weight cannot be negative.'); return; }
    if (next && parsedRpe !== null && (parsedRpe < 0 || parsedRpe > 10)) { Alert.alert('Invalid RPE', 'RPE must be between 0 and 10.'); return; }
    setCompleted(next); void save({ completed: next }); onComplete(next);
  };
  const copyPrevious = () => { if (!previous) return; setWeight(previous.weight?.toString() ?? ''); setReps(previous.reps?.toString() ?? ''); setRpe(previous.rpe?.toString() ?? ''); setType(previous.setType); void onSave({ weight: previous.weight, reps: previous.reps, rpe: previous.rpe, setType: previous.setType, completed, notes: notes || null }); };
  return <View style={[styles.card, completed && styles.complete]}><View style={styles.head}><Text style={styles.number}>Set {set.setNumber}</Text><View style={styles.headActions}>{previous ? <Pressable onPress={copyPrevious}><Text style={styles.copy}>Copy previous</Text></Pressable> : null}<Pressable onPress={onDelete}><Text style={styles.delete}>Delete</Text></Pressable><Pressable accessibilityRole="checkbox" accessibilityState={{ checked: completed }} onPress={toggle} style={[styles.check, completed && styles.checked]}><Text style={styles.checkText}>{completed ? '✓' : ''}</Text></Pressable></View></View>
    <View style={styles.inputs}><AppInput containerStyle={styles.flex} label="Weight" keyboardType="decimal-pad" value={weight} onChangeText={setWeight} onBlur={() => void save()} /><AppInput containerStyle={styles.flex} label="Reps" keyboardType="number-pad" value={reps} onChangeText={setReps} onBlur={() => void save()} /><AppInput containerStyle={styles.flex} label="RPE" keyboardType="decimal-pad" value={rpe} onChangeText={setRpe} onBlur={() => void save()} /></View>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.types}>{setTypes.map((item) => <FilterChip key={item} label={item} selected={type === item} onPress={() => { setType(item); void save({ setType: item }); }} />)}</ScrollView>
    <AppInput label="Set notes" value={notes} onChangeText={setNotes} onBlur={() => void save()} />
  </View>;
}
const styles = StyleSheet.create({ card: { padding: spacing.md, borderRadius: radius.md, backgroundColor: colors.surfaceElevated, borderWidth: 1, borderColor: colors.border, gap: spacing.md }, complete: { borderColor: colors.accent, backgroundColor: '#10291B' }, head: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, number: { ...typography.label, color: colors.text }, headActions: { flexDirection: 'row', alignItems: 'center', gap: spacing.md }, copy: { ...typography.caption, color: colors.accent }, delete: { ...typography.caption, color: colors.danger }, check: { width: 34, height: 34, borderRadius: 17, borderWidth: 2, borderColor: colors.textMuted, alignItems: 'center', justifyContent: 'center' }, checked: { backgroundColor: colors.accent, borderColor: colors.accent }, checkText: { color: colors.accentText, fontWeight: '900' }, inputs: { flexDirection: 'row', gap: spacing.sm }, flex: { flex: 1 }, types: { gap: spacing.sm } });
