import { router, useFocusEffect } from 'expo-router';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { ActivityIndicator, FlatList, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import AsyncStorage from '@react-native-async-storage/async-storage';

import { FilterChip } from '@/components/FilterChip';
import { AppInput } from '@/components/AppInput';
import { Header } from '@/components/Header';
import { HistoryEmptyState } from '@/components/HistoryEmptyState';
import { SearchBar } from '@/components/SearchBar';
import { WorkoutHistoryCard } from '@/components/WorkoutHistoryCard';
import { WorkoutHistorySectionHeader } from '@/components/WorkoutHistorySectionHeader';
import { WorkoutHistoryCalendar } from '@/components/WorkoutHistoryCalendar';
import { WorkoutHistoryTimeline } from '@/components/WorkoutHistoryTimeline';
import { colors } from '@/constants/colors'; import { spacing } from '@/constants/spacing'; import { typography } from '@/constants/typography';
import { useDatabase } from '@/hooks/useDatabase';
import { listExercises } from '@/repositories/exerciseRepository'; import { getAllPlans } from '@/repositories/workoutPlanRepository'; import { getCompletedWorkoutsPage } from '@/repositories/workoutRepository';
import { groupWorkoutHistory } from '@/services/workoutHistoryService'; import type { Exercise } from '@/types/exercise'; import type { WorkoutHistoryFilter, WorkoutHistoryItem, WorkoutHistorySort } from '@/types/workout'; import type { WorkoutPlan } from '@/types/workoutPlan'; import { getUserMessage } from '@/utils/errors';
import type{WorkoutHistoryView}from'@/types/history';

const PAGE_SIZE = 20;
type Row = { kind: 'header'; id: string; title: string } | { kind: 'workout'; id: string; workout: WorkoutHistoryItem };
const initialFilter: WorkoutHistoryFilter = { search: '', datePreset: 'all' };
const sorts: { value: WorkoutHistorySort; label: string }[] = [{ value: 'newest', label: 'Newest' }, { value: 'oldest', label: 'Oldest' }, { value: 'longest', label: 'Longest' }, { value: 'volume', label: 'Volume' }, { value: 'sets', label: 'Most Sets' }];

export default function HistoryScreen() {
  const db = useDatabase(); const [search, setSearch] = useState(''); const [filter, setFilter] = useState(initialFilter); const [sort, setSort] = useState<WorkoutHistorySort>('newest'); const [view,setView]=useState<WorkoutHistoryView>('list');const[selectedDayIds,setSelectedDayIds]=useState<string[]>([]); const [items, setItems] = useState<WorkoutHistoryItem[]>([]); const itemsRef = useRef<WorkoutHistoryItem[]>([]); const [loading, setLoading] = useState(true); const [loadingMore, setLoadingMore] = useState(false); const [hasMore, setHasMore] = useState(true); const [error, setError] = useState<string | null>(null); const [showFilters, setShowFilters] = useState(false); const [plans, setPlans] = useState<WorkoutPlan[]>([]); const [exercises, setExercises] = useState<Exercise[]>([]); const requestRef = useRef(false);
  useEffect(()=>{void AsyncStorage.getItem('history_view').then(value=>{if(value==='list'||value==='calendar'||value==='timeline')setView(value)})},[]);const chooseView=(value:WorkoutHistoryView)=>{setView(value);setSelectedDayIds([]);void AsyncStorage.setItem('history_view',value)};
  useEffect(() => { itemsRef.current = items; }, [items]);
  useEffect(() => { const timer = setTimeout(() => setFilter((value) => ({ ...value, search })), 300); return () => clearTimeout(timer); }, [search]);
  useEffect(() => { if (showFilters && !plans.length) void Promise.all([getAllPlans(db), listExercises(db)]).then(([nextPlans, nextExercises]) => { setPlans(nextPlans); setExercises(nextExercises); }); }, [db, plans.length, showFilters]);
  const load = useCallback(async (append = false) => { if (requestRef.current) return; requestRef.current = true; if (append) setLoadingMore(true); else setLoading(true); setError(null); try { const offset = append ? itemsRef.current.length : 0; const limit=view==='list'?PAGE_SIZE:200;const page = await getCompletedWorkoutsPage(db, filter, sort, offset, limit); setItems((current) => append ? [...current, ...page] : page); setHasMore(view==='list'&&page.length === PAGE_SIZE); } catch (caught) { setError(getUserMessage(caught, 'Could not load workout history.')); } finally { requestRef.current = false; setLoading(false); setLoadingMore(false); } }, [db, filter, sort,view]);
  useFocusEffect(useCallback(() => { void load(false); }, [load]));
  const rows = useMemo<Row[]>(() => groupWorkoutHistory(items).flatMap((section) => [{ kind: 'header' as const, id: `header-${section.title}`, title: section.title }, ...section.data.map((workout) => ({ kind: 'workout' as const, id: workout.id, workout }))]), [items]);
  const filtered = filter.datePreset !== 'all' || filter.workoutType || filter.planId || filter.exerciseId || filter.minimumDurationSeconds || filter.hasNotes;
  return <SafeAreaView edges={['top']} style={styles.screen}><Header title="History" action={<Pressable onPress={() => setShowFilters((value) => !value)}><Text style={styles.action}>{showFilters ? 'Done' : 'Filters'}</Text></Pressable>} /><View style={styles.controls}><View style={styles.chips}>{(['list','calendar','timeline']as const).map(value=><FilterChip key={value} label={value[0].toUpperCase()+value.slice(1)} selected={view===value} onPress={()=>chooseView(value)}/>)}</View><SearchBar value={search} onChangeText={setSearch} placeholder="Search workouts, exercises, plans…" /><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{sorts.map((item) => <FilterChip key={item.value} label={item.label} selected={sort === item.value} onPress={() => setSort(item.value)} />)}</ScrollView>{showFilters ? <FilterPanel filter={filter} setFilter={setFilter} plans={plans} exercises={exercises} /> : null}</View>
    {error ? <View style={styles.message}><Text style={styles.error}>{error}</Text><Pressable onPress={() => void load(false)}><Text style={styles.action}>Try again</Text></Pressable></View> : loading ? <View style={styles.message}><ActivityIndicator size="large" color={colors.accent} /></View> : view==='list'?<FlatList data={rows} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} renderItem={({ item }) => item.kind === 'header' ? <WorkoutHistorySectionHeader title={item.title} /> : <WorkoutHistoryCard workout={item.workout} onPress={() => router.push(`/workout/${item.workout.id}`)} />} ListEmptyComponent={<HistoryEmptyState mode={search.trim() ? 'search' : filtered ? 'filter' : 'none'} />} ListFooterComponent={loadingMore ? <ActivityIndicator style={styles.footer} color={colors.accent} /> : null} onEndReached={() => { if (hasMore && !loadingMore) void load(true); }} onEndReachedThreshold={0.4} />:<ScrollView contentContainerStyle={styles.list}>{items.length===0?<HistoryEmptyState mode={search.trim()?'search':filtered?'filter':'none'}/>:view==='calendar'?<><WorkoutHistoryCalendar items={items} onSelect={setSelectedDayIds}/>{selectedDayIds.map(id=>{const workout=items.find(item=>item.id===id);return workout?<WorkoutHistoryCard key={id} workout={workout} onPress={()=>router.push(`/workout/${id}`)}/>:null})}</>:<WorkoutHistoryTimeline items={items} onPress={id=>router.push(`/workout/${id}`)}/>}</ScrollView>}
  </SafeAreaView>;
}

function FilterPanel({ filter, setFilter, plans, exercises }: { filter: WorkoutHistoryFilter; setFilter: React.Dispatch<React.SetStateAction<WorkoutHistoryFilter>>; plans: WorkoutPlan[]; exercises: Exercise[] }) {
  const dates: { value: WorkoutHistoryFilter['datePreset']; label: string }[] = [{ value: '7d', label: '7 Days' }, { value: '30d', label: '30 Days' }, { value: '3m', label: '3 Months' }, { value: 'year', label: 'This Year' }, { value: 'all', label: 'All Time' }, { value: 'custom', label: 'Custom' }];
  return <View style={styles.filter}><Text style={styles.label}>Date</Text><ScrollView horizontal contentContainerStyle={styles.chips}>{dates.map((item) => <FilterChip key={item.value} label={item.label} selected={filter.datePreset === item.value} onPress={() => setFilter((value) => ({ ...value, datePreset: item.value }))} />)}</ScrollView>{filter.datePreset === 'custom' ? <View style={styles.row}><AppInput containerStyle={styles.flex} label="From (YYYY-MM-DD)" value={filter.dateFrom ?? ''} onChangeText={(dateFrom) => setFilter((value) => ({ ...value, dateFrom }))} /><AppInput containerStyle={styles.flex} label="To (YYYY-MM-DD)" value={filter.dateTo ?? ''} onChangeText={(dateTo) => setFilter((value) => ({ ...value, dateTo }))} /></View> : null}<Text style={styles.label}>Type and duration</Text><ScrollView horizontal contentContainerStyle={styles.chips}><FilterChip label="All Types" selected={!filter.workoutType} onPress={() => setFilter((value) => ({ ...value, workoutType: undefined }))} /><FilterChip label="Strength" selected={filter.workoutType === 'strength'} onPress={() => setFilter((value) => ({ ...value, workoutType: 'strength' }))} /><FilterChip label="Mixed" selected={filter.workoutType === 'mixed'} onPress={() => setFilter((value) => ({ ...value, workoutType: 'mixed' }))} /><FilterChip label="30+ min" selected={filter.minimumDurationSeconds === 1800} onPress={() => setFilter((value) => ({ ...value, minimumDurationSeconds: value.minimumDurationSeconds ? undefined : 1800 }))} /><FilterChip label="Has Notes" selected={Boolean(filter.hasNotes)} onPress={() => setFilter((value) => ({ ...value, hasNotes: !value.hasNotes }))} /></ScrollView>
    <Text style={styles.label}>Plan</Text><ScrollView horizontal contentContainerStyle={styles.chips}><FilterChip label="Any Plan" selected={!filter.planId} onPress={() => setFilter((value) => ({ ...value, planId: undefined }))} />{plans.map((plan) => <FilterChip key={plan.id} label={plan.name} selected={filter.planId === plan.id} onPress={() => setFilter((value) => ({ ...value, planId: plan.id }))} />)}</ScrollView>
    <Text style={styles.label}>Exercise</Text><ScrollView horizontal contentContainerStyle={styles.chips}><FilterChip label="Any Exercise" selected={!filter.exerciseId} onPress={() => setFilter((value) => ({ ...value, exerciseId: undefined }))} />{exercises.map((exercise) => <FilterChip key={exercise.id} label={exercise.name} selected={filter.exerciseId === exercise.id} onPress={() => setFilter((value) => ({ ...value, exerciseId: exercise.id }))} />)}</ScrollView><Pressable onPress={() => setFilter(initialFilter)}><Text style={styles.clear}>Clear filters</Text></Pressable>
  </View>;
}
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.background }, controls: { paddingHorizontal: spacing.lg, gap: spacing.sm }, chips: { gap: spacing.sm }, list: { paddingHorizontal: spacing.lg, paddingBottom: spacing.xxl, flexGrow: 1 }, action: { ...typography.label, color: colors.accent }, message: { flex: 1, justifyContent: 'center', alignItems: 'center', gap: spacing.md }, error: { ...typography.body, color: colors.danger }, footer: { margin: spacing.lg }, filter: { gap: spacing.sm, paddingBottom: spacing.md }, label: { ...typography.label, color: colors.text }, clear: { ...typography.label, color: colors.danger, paddingVertical: spacing.sm }, row: { flexDirection: 'row', gap: spacing.sm }, flex: { flex: 1 } });
