import { router, useFocusEffect } from 'expo-router';
import { useCallback, useMemo, useState } from 'react';
import { ActivityIndicator, Alert, ScrollView, StyleSheet, Text, View } from 'react-native';

import { ActiveWorkoutBanner } from '@/components/ActiveWorkoutBanner';
import { AppButton } from '@/components/AppButton';
import { AppScreen } from '@/components/AppScreen';
import { EmptyState } from '@/components/EmptyState';
import { Header } from '@/components/Header';
import { SearchBar } from '@/components/SearchBar';
import { SectionHeader } from '@/components/SectionHeader';
import { TodayWorkoutCard } from '@/components/TodayWorkoutCard';
import { WorkoutPlanCard } from '@/components/WorkoutPlanCard';
import { colors } from '@/constants/colors'; import { radius,spacing } from '@/constants/spacing'; import { typography } from '@/constants/typography';
import { useDatabase } from '@/hooks/useDatabase'; import { useStartWorkout } from '@/hooks/useStartWorkout';
import { getAllPlans } from '@/repositories/workoutPlanRepository';
import { getNextProgramWorkout,getScheduledWorkoutsForDate } from '@/repositories/scheduledWorkoutRepository';
import { createWorkoutFromCompletedWorkout,getActiveWorkout,getMostRecentCompletedWorkout } from '@/repositories/workoutRepository';
import { restoreScheduledAfterDiscard } from '@/repositories/workoutLaunchRepository';
import { localTodayKey,orderTodaysWorkouts } from '@/services/workoutLaunchService';
import type { ScheduledWorkout } from '@/types/scheduledWorkout'; import type { WorkoutPlan } from '@/types/workoutPlan'; import type { ActiveWorkout,WorkoutHistoryItem } from '@/types/workout'; import { getUserMessage } from '@/utils/errors';

export default function StartScreen(){const db=useDatabase();const launch=useStartWorkout(db);const[active,setActive]=useState<ActiveWorkout|null>();const[today,setToday]=useState<ScheduledWorkout[]>([]);const[next,setNext]=useState<ScheduledWorkout|null>(null);const[recent,setRecent]=useState<WorkoutHistoryItem|null>(null);const[showLibrary,setShowLibrary]=useState(false);const[plans,setPlans]=useState<WorkoutPlan[]>([]);const[search,setSearch]=useState('');const[loading,setLoading]=useState(true);
 const load=useCallback(async()=>{setLoading(true);try{const key=localTodayKey();const[a,t,n,r]=await Promise.all([getActiveWorkout(db),getScheduledWorkoutsForDate(db,key),getNextProgramWorkout(db,key),getMostRecentCompletedWorkout(db)]);setActive(a);setToday(orderTodaysWorkouts(t));setNext(n);setRecent(r);}catch(e){Alert.alert('Could not load Start Workout',getUserMessage(e));}finally{setLoading(false)}},[db]);
 useFocusEffect(useCallback(()=>{void load()},[load]));
 const openLibrary=async()=>{setShowLibrary(true);try{setPlans(await getAllPlans(db))}catch(e){Alert.alert('Could not load workouts',getUserMessage(e))}};
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return q?plans.filter(p=>`${p.name} ${p.description??''} ${p.workoutType}`.toLowerCase().includes(q)):plans},[plans,search]);
 const safely=async(action:()=>Promise<unknown>)=>{if(active){Alert.alert('A workout is already in progress.','Resume or finish it before starting another.',[{text:'Resume Current Workout',onPress:()=>router.push({pathname:'/workout/active',params:{id:active.id}})},{text:'Finish Current Workout',onPress:()=>router.push({pathname:'/workout/active',params:{id:active.id,finish:'1'}})},{text:'Discard Current and Start',style:'destructive',onPress:()=>void restoreScheduledAfterDiscard(db,active.id,true).then(()=>action()).catch(e=>Alert.alert('Could not start workout',getUserMessage(e)))},{text:'Cancel',style:'cancel'}]);return}try{await action()}catch(e){Alert.alert('Could not start workout',getUserMessage(e))}};
 const discard=()=>active&&Alert.alert('Discard workout?','Logged progress will be permanently removed.',[{text:'Cancel',style:'cancel'},{text:'Discard and keep scheduled',onPress:()=>void restoreScheduledAfterDiscard(db,active.id,true).then(load)},{text:'Discard and mark skipped',style:'destructive',onPress:()=>void restoreScheduledAfterDiscard(db,active.id,false).then(load)}]);
 const eligible=today.filter(x=>x.status==='scheduled'||x.status==='missed'||x.status==='skipped');const status=today.filter(x=>!eligible.includes(x));
 if(loading&&active===undefined)return <AppScreen header={<Header title="Start Workout" action={<AppButton label="Plates" variant="secondary" onPress={()=>router.push('/tools/plate-calculator')}/>}/>}><ActivityIndicator style={{flex:1}} color={colors.accent}/></AppScreen>;
 return <AppScreen header={<Header title="Start Workout" action={<AppButton label="Plates" variant="secondary" onPress={()=>router.push('/tools/plate-calculator')}/>}/>}><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled">
  <Text accessibilityRole="header" style={s.question}>What do you want to train right now?</Text>
  {active?<><SectionHeader>Active Workout</SectionHeader><ActiveWorkoutBanner workout={active} onResume={()=>router.push({pathname:'/workout/active',params:{id:active.id}})} onEnd={()=>router.push({pathname:'/workout/active',params:{id:active.id,finish:'1'}})} onDiscard={discard}/></>:null}
  <SectionHeader>Today&apos;s Workouts</SectionHeader>
  {eligible.length?eligible.map(item=><TodayWorkoutCard key={item.id} item={item} busy={launch.busyKey===`scheduled:${item.id}`} onStart={()=>void safely(()=>launch.startScheduled(item.id))} onPreview={()=>router.push({pathname:'/start/preview',params:{scheduledId:item.id}})} onMove={()=>router.push({pathname:'/calendar/[id]',params:{id:item.id}})} onEdit={()=>router.push({pathname:'/calendar/[id]',params:{id:item.id}})}/>):<EmptyState title="No workout planned for today" message="Choose something that fits today, or add a workout to your calendar." actionLabel="Start Something Else" onAction={()=>void openLibrary()}/>} 
  {!eligible.length?<View style={s.row}><AppButton label="View Calendar" variant="secondary" onPress={()=>router.push('/calendar')} style={s.flex}/><AppButton label="Schedule Workout" variant="secondary" onPress={()=>router.push('/calendar/schedule')} style={s.flex}/></View>:null}
  {status.length?<View style={s.status}><Text style={s.statusTitle}>Today Status</Text>{status.map(item=><Text key={item.id} style={s.muted}>{item.status.replace('_',' ')} · {item.snapshotName}</Text>)}</View>:null}
  {!active&&next?<><SectionHeader>Next in Your Program</SectionHeader><View style={s.card}><Text style={s.title}>{next.snapshotName}</Text><Text style={s.muted}>Week {next.programWeekNumber??'—'} · scheduled {next.scheduledDate}</Text><View style={s.row}><AppButton label="Preview" variant="secondary" onPress={()=>router.push({pathname:'/start/preview',params:{scheduledId:next.id}})} style={s.flex}/><AppButton label="Start Early" onPress={()=>router.push({pathname:'/start/preview',params:{scheduledId:next.id,early:'1'}})} style={s.flex}/></View></View></>:null}
  <SectionHeader>Quick Start</SectionHeader><View style={s.quick}><AppButton label="Quick Strength" variant="secondary" onPress={()=>router.push({pathname:'/start/quick',params:{type:'strength'}})} style={s.quickButton}/><AppButton label="Quick Run" variant="secondary" onPress={()=>router.push({pathname:'/start/quick',params:{type:'running'}})} style={s.quickButton}/><AppButton label="Quick Ride" variant="secondary" onPress={()=>router.push({pathname:'/start/quick',params:{type:'cycling'}})} style={s.quickButton}/><AppButton label="Blank Workout" variant="secondary" onPress={()=>router.push({pathname:'/start/quick',params:{type:'blank'}})} style={s.quickButton}/></View>
  <SectionHeader>Start Something Else</SectionHeader><AppButton label={showLibrary?'Hide Workout Library':'Browse My and Built-in Workouts'} variant="secondary" onPress={()=>showLibrary?setShowLibrary(false):void openLibrary()}/>
  {showLibrary?<><SearchBar value={search} onChangeText={setSearch} placeholder="Search workouts, types, exercises"/>{filtered.map(plan=><WorkoutPlanCard key={plan.id} plan={plan} onPress={()=>router.push({pathname:'/start/preview',params:{planId:plan.id,source:plan.isBuiltin?'BUILT_IN_WORKOUT':'WORKOUT_TEMPLATE'}})}/>)}</>:null}
  {recent?<><SectionHeader>Recent Workout</SectionHeader><View style={s.card}><Text style={s.title}>{recent.name}</Text><Text style={s.muted}>{recent.exerciseCount} exercises · {recent.completedSetCount} completed sets</Text><AppButton label="Start Again" variant="secondary" onPress={()=>void safely(async()=>{const id=await createWorkoutFromCompletedWorkout(db,recent.id);router.push({pathname:'/workout/active',params:{id}})})}/></View></>:null}
 </ScrollView></AppScreen>}
const s=StyleSheet.create({content:{paddingVertical:spacing.lg,paddingBottom:spacing.xxl,gap:spacing.md},question:{...typography.title,color:colors.text},card:{padding:spacing.lg,borderRadius:radius.lg,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,gap:spacing.sm},title:{...typography.heading,color:colors.text},muted:{...typography.caption,color:colors.textMuted,textTransform:'capitalize'},row:{flexDirection:'row',gap:spacing.sm},flex:{flex:1},quick:{flexDirection:'row',flexWrap:'wrap',gap:spacing.sm},quickButton:{width:'47%'},status:{backgroundColor:colors.surface,padding:spacing.md,borderRadius:radius.md,gap:spacing.xs},statusTitle:{...typography.label,color:colors.text}});
