import { router, useFocusEffect } from 'expo-router'; import { useCallback, useState } from 'react'; import { ActivityIndicator, Alert, ScrollView, StyleSheet, Text, View } from 'react-native';
import { AppButton } from '@/components/AppButton'; import { AppInput } from '@/components/AppInput'; import { AppScreen } from '@/components/AppScreen'; import { Header } from '@/components/Header'; import { SectionHeader } from '@/components/SectionHeader'; import { WorkoutPlanCard } from '@/components/WorkoutPlanCard';
import { colors } from '@/constants/colors'; import { radius, spacing } from '@/constants/spacing'; import { typography } from '@/constants/typography'; import { useDatabase } from '@/hooks/useDatabase'; import { getAllPlans } from '@/repositories/workoutPlanRepository'; import { createEmptyWorkout, createWorkoutFromPlan, discardWorkout, getActiveWorkout } from '@/repositories/workoutRepository'; import type { WorkoutPlan } from '@/types/workoutPlan'; import { getUserMessage } from '@/utils/errors'; import type { ActiveWorkout } from '@/types/workout';
export default function StartScreen() {
  const db = useDatabase(); const [active, setActive] = useState<ActiveWorkout | null>(); const [plans, setPlans] = useState<WorkoutPlan[]>([]); const [name, setName] = useState(''); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { const [workout, allPlans] = await Promise.all([getActiveWorkout(db), getAllPlans(db)]); setActive(workout); setPlans(allPlans); }, [db]); useFocusEffect(useCallback(() => { void load(); }, [load]));
  const run = async (action: () => Promise<string>) => { setBusy(true); try { const id = await action(); router.push({ pathname: '/workout/active', params: { id } }); } catch (caught) { Alert.alert('Could not start workout', getUserMessage(caught)); } finally { setBusy(false); } };
  if (active === undefined) return <AppScreen header={<Header title="Start" />}><ActivityIndicator style={styles.flex} color={colors.accent} /></AppScreen>;
  return <AppScreen header={<Header title="Start" />}><ScrollView contentContainerStyle={styles.content}>
    {active ? <View style={styles.active}><Text style={styles.activeTitle}>Workout in progress</Text><Text style={styles.muted}>{active.name}</Text><AppButton label="Resume" onPress={() => router.push({ pathname: '/workout/active', params: { id: active.id } })} /><AppButton label="Finish" variant="secondary" onPress={() => router.push({ pathname: '/workout/active', params: { id: active.id, finish: '1' } })} /><AppButton label="Discard" variant="danger" onPress={() => Alert.alert('Discard workout?', 'All logged sets will be permanently deleted.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Discard', style: 'destructive', onPress: () => void discardWorkout(db, active.id).then(load) }])} /></View> : <>
      <SectionHeader>Empty Workout</SectionHeader><View style={styles.card}><AppInput label="Workout name" placeholder="Evening Strength" value={name} onChangeText={setName} /><AppButton label="Start Empty Strength Workout" loading={busy} onPress={() => void run(() => createEmptyWorkout(db, name))} /></View>
      <AppButton label="Log Cardio Session" variant="secondary" onPress={() => router.push('/cardio/create')} />
      <AppButton label="Repeat Last Workout" variant="secondary" onPress={() => Alert.alert('Coming later', 'Repeat from workout history will be implemented in Phase 4.')} />
      <SectionHeader>Start from a Plan</SectionHeader>{plans.map((plan) => <WorkoutPlanCard key={plan.id} plan={plan} onPress={() => void run(async () => { const full = await import('@/repositories/workoutPlanRepository').then((module) => module.getPlanById(db, plan.id)); if (!full) throw new Error('Plan not found'); return createWorkoutFromPlan(db, full); })} />)}
    </>}
  </ScrollView></AppScreen>;
}
const styles = StyleSheet.create({ flex: { flex: 1 }, content: { paddingVertical: spacing.lg, paddingBottom: spacing.xxl, gap: spacing.md }, active: { padding: spacing.lg, borderRadius: radius.lg, backgroundColor: colors.surface, gap: spacing.md }, activeTitle: { ...typography.heading, color: colors.text }, muted: { ...typography.body, color: colors.textMuted }, card: { padding: spacing.lg, borderRadius: radius.lg, backgroundColor: colors.surface, gap: spacing.md } });
