import { format } from 'date-fns'; import { router, useFocusEffect, useLocalSearchParams } from 'expo-router'; import { useCallback, useState } from 'react'; import { ActivityIndicator, Alert, ScrollView, StyleSheet, Text, View } from 'react-native';
import { AppButton } from '@/components/AppButton'; import { CardioSummaryCard } from '@/components/CardioSummaryCard'; import { PersonalRecordBadge } from '@/components/PersonalRecordBadge'; import { PlannedPerformedComparison } from '@/components/PlannedPerformedComparison'; import { WorkoutGroupCard } from '@/components/WorkoutGroupCard'; import { WorkoutExerciseHistoryCard } from '@/components/WorkoutExerciseHistoryCard'; import { colors } from '@/constants/colors'; import { radius, spacing } from '@/constants/spacing'; import { typography } from '@/constants/typography'; import { useDatabase } from '@/hooks/useDatabase'; import { getRecordsForWorkout } from '@/repositories/personalRecordRepository'; import { getHistoryCorrections } from '@/repositories/historyRepository'; import { createWorkoutFromCompletedWorkout, deleteWorkout, discardWorkout, duplicateWorkoutAsPlan, getActiveWorkout, getWorkoutDetails } from '@/repositories/workoutRepository'; import type { PersonalRecord } from '@/types/personalRecord'; import type { HistoryCorrectionAudit } from '@/types/history'; import type { WorkoutDetails } from '@/types/workout'; import { getUserMessage } from '@/utils/errors';
const duration = (seconds: number) => `${Math.floor(seconds / 60)} min ${seconds % 60} sec`;
export default function WorkoutDetailsScreen() { const { id } = useLocalSearchParams<{ id: string }>(); const db = useDatabase(); const [workout, setWorkout] = useState<WorkoutDetails | null>(); const [records, setRecords] = useState<PersonalRecord[]>([]);const[corrections,setCorrections]=useState<HistoryCorrectionAudit[]>([]); const [busy, setBusy] = useState(false); const load = useCallback(async () => { if (id) { setWorkout(await getWorkoutDetails(db, id)); setRecords(await getRecordsForWorkout(db, id));setCorrections(await getHistoryCorrections(db,id)); } }, [db, id]); useFocusEffect(useCallback(() => { void load(); }, [load]));
  const repeat = async () => { if (!workout) return; const active = await getActiveWorkout(db); if (active) { Alert.alert('Workout already active', 'Resume it or discard it before repeating this workout.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Resume Current', onPress: () => router.push({ pathname: '/workout/active', params: { id: active.id } }) }, { text: 'Discard and Repeat', style: 'destructive', onPress: () => void discardWorkout(db, active.id).then(startRepeat) }]); return; } await startRepeat(); };
  const startRepeat = async () => { if (!workout) return; try { setBusy(true); const nextId = await createWorkoutFromCompletedWorkout(db, workout.id); router.replace({ pathname: '/workout/active', params: { id: nextId } }); } catch (error) { Alert.alert('Repeat failed', getUserMessage(error, 'Could not repeat this workout.')); } finally { setBusy(false); } };
  const duplicate = async () => { if (!workout) return; try { setBusy(true); const planId = await duplicateWorkoutAsPlan(db, workout.id); router.push(`/plans/${planId}`); } catch (error) { Alert.alert('Plan creation failed', getUserMessage(error, 'Could not duplicate this workout as a plan.')); } finally { setBusy(false); } };
  const remove = () => { if (!workout) return; Alert.alert('Delete workout?', `${workout.name} from ${format(new Date(workout.startedAt), 'MMM d, yyyy')} will be permanently deleted.`, [{ text: 'Cancel', style: 'cancel' }, { text: 'Delete', style: 'destructive', onPress: () => void deleteWorkout(db, workout.id).then(() => { Alert.alert('Workout deleted'); router.back(); }).catch((error) => Alert.alert('Delete failed', getUserMessage(error))) }]); };
  if (workout === undefined) return <View style={styles.center}><ActivityIndicator color={colors.accent} /></View>; if (!workout) return <View style={styles.center}><Text style={styles.title}>Workout not found</Text><Text style={styles.muted}>It may have been deleted.</Text><AppButton label="Back to History" onPress={() => router.replace('/history')} /></View>;
  const summary = workout.summary; return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><Text style={styles.title}>{workout.name}</Text><Text style={styles.muted}>{format(new Date(workout.startedAt), 'EEEE, MMMM d, yyyy · h:mm a')}</Text>{workout.correctedLocalDate?<Text style={styles.plan}>Corrected display date: {workout.correctedLocalDate}</Text>:null}<Text style={styles.muted}>Completed {workout.completedAt ? format(new Date(workout.completedAt), 'h:mm a') : '—'} · {duration(summary.durationSeconds)} · {workout.workoutType}</Text><Text style={styles.plan}>{workout.completionQuality?.toUpperCase()??'COMPLETED'}{workout.sessionSourceType?` · ${workout.sessionSourceType.replaceAll('_',' ')}`:''}</Text>{workout.planName ? <Text style={styles.plan}>Source plan: {workout.planName}</Text> : null}<PersonalRecordBadge records={records} />{workout.notes ? <View style={styles.notes}><Text style={styles.body}>{workout.notes}</Text></View> : null}
    <View style={styles.stats}><Stat value={String(summary.exerciseCount)} label="Exercises" /><Stat value={String(summary.completedSetCount)} label="Sets" /><Stat value={String(summary.totalRepetitions)} label="Reps" /></View><View style={styles.stats}><Stat value={summary.totalVolume.toFixed(1)} label="kg volume" /><Stat value={summary.averageRpe?.toFixed(1) ?? '—'} label="Avg RPE" /></View>
    <PlannedPerformedComparison workout={workout}/>{corrections.length?<View style={styles.notes}><Text style={styles.body}>Correction history</Text>{corrections.map(item=><Text key={item.id} style={styles.muted}>{item.fieldName.replaceAll('_',' ')} · {format(new Date(item.createdAt),'MMM d, yyyy')} · {item.reason}</Text>)}</View>:null}<View style={styles.actions}><AppButton label="Repeat Workout" loading={busy} onPress={() => void repeat()} /><AppButton label="Correct History Metadata" variant="secondary" onPress={() => router.push(`/workout/correct/${workout.id}`)} /><AppButton label="Duplicate as Plan" variant="secondary" onPress={() => void duplicate()} /><AppButton label="Delete Workout" variant="danger" onPress={remove} /></View>
    {workout.groups.map((group)=><WorkoutGroupCard key={group.id} group={group}/>)}{workout.cardioSessions.map((session)=><CardioSummaryCard key={session.id} session={session}/>)}{workout.exercises.map((item) => <WorkoutExerciseHistoryCard key={item.id} item={item} />)}
  </ScrollView>; }
function Stat({ value, label }: { value: string; label: string }) { return <View style={styles.stat}><Text style={styles.statValue}>{value}</Text><Text style={styles.muted}>{label}</Text></View>; }
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.background }, content: { padding: spacing.lg, paddingBottom: spacing.xxl, gap: spacing.md }, center: { flex: 1, backgroundColor: colors.background, justifyContent: 'center', alignItems: 'center', padding: spacing.xl, gap: spacing.md }, title: { ...typography.title, color: colors.text }, body: { ...typography.body, color: colors.text }, muted: { ...typography.caption, color: colors.textMuted }, plan: { ...typography.label, color: colors.accent }, notes: { padding: spacing.md, borderRadius: radius.md, backgroundColor: colors.surface }, stats: { flexDirection: 'row', gap: spacing.sm }, stat: { flex: 1, alignItems: 'center', padding: spacing.md, borderRadius: radius.md, backgroundColor: colors.surface }, statValue: { ...typography.heading, color: colors.text }, actions: { gap: spacing.sm, marginVertical: spacing.sm } });
