import { router, useFocusEffect, useLocalSearchParams } from 'expo-router'; import { useCallback, useEffect, useState } from 'react'; import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { AppButton } from '@/components/AppButton'; import { AppInput } from '@/components/AppInput'; import { RestTimer } from '@/components/RestTimer'; import { ReorderControls } from '@/components/ReorderControls'; import { WorkoutSetRow } from '@/components/WorkoutSetRow'; import { colors } from '@/constants/colors'; import { radius, spacing } from '@/constants/spacing'; import { typography } from '@/constants/typography'; import { useRestTimer } from '@/hooks/useRestTimer'; import { useDatabase } from '@/hooks/useDatabase';
import { addWorkoutSet, deleteWorkoutSet, discardWorkout, finishWorkout, getWorkoutById, removeWorkoutExercise, reorderWorkoutExercise, updateWorkoutNotes, updateWorkoutSet, workoutExerciseHasCompletedSets } from '@/repositories/workoutRepository'; import { assertCanFinish, elapsedSeconds, summarizeWorkout } from '@/services/workoutService'; import type { ActiveWorkout, WorkoutExercise } from '@/types/workout'; import { getUserMessage } from '@/utils/errors';
const clock = (seconds: number) => `${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, '0')}`;
export default function ActiveWorkoutScreen() {
  const { id, finish } = useLocalSearchParams<{ id: string; finish?: string }>(); const db = useDatabase(); const [workout, setWorkout] = useState<ActiveWorkout | null>(); const [workoutNotes, setWorkoutNotes] = useState(''); const [now, setNow] = useState(Date.now()); const timer = useRestTimer(id ?? 'none');
  const load = useCallback(async () => { if (id) { const result = await getWorkoutById(db, id); setWorkout(result); setWorkoutNotes(result?.notes ?? ''); } }, [db, id]); useFocusEffect(useCallback(() => { void load(); }, [load])); useEffect(() => { const interval = setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(interval); }, []);
  const requestFinish = useCallback(() => { if (!workout) return; try { assertCanFinish(workout); const summary = summarizeWorkout(workout); Alert.alert('Finish workout?', `${summary.completedExercises} exercises · ${summary.completedSets} sets · ${summary.totalRepetitions} reps · ${summary.totalVolume.toFixed(1)} kg volume`, [{ text: 'Continue', style: 'cancel' }, { text: 'Discard', style: 'destructive', onPress: () => void discardWorkout(db, workout.id).then(() => router.replace('/start')) }, { text: 'Save and Finish', onPress: () => void finishWorkout(db, workout).then(() => router.replace({ pathname: '/workout/summary', params: { id: workout.id } })) }]); } catch (caught) { Alert.alert('Cannot finish yet', getUserMessage(caught, caught instanceof Error ? caught.message : 'Complete a set first.')); } }, [db, workout]);
  useEffect(() => { if (finish === '1' && workout) requestFinish(); }, [finish, requestFinish, workout]);
  if (workout === undefined) return <View style={styles.center}><ActivityIndicator size="large" color={colors.accent} /></View>; if (!workout) return <View style={styles.center}><Text style={styles.muted}>Workout not found.</Text></View>;
  const summary = summarizeWorkout(workout); const move = async (index: number, direction: -1 | 1) => { const ids = workout.exercises.map((item) => item.id); const [item] = ids.splice(index, 1); ids.splice(index + direction, 0, item); await reorderWorkoutExercise(db, workout.id, ids); await load(); };
  const remove = async (item: WorkoutExercise) => { const completed = await workoutExerciseHasCompletedSets(db, item.id); const execute = () => void removeWorkoutExercise(db, item.id).then(load); if (completed) Alert.alert('Remove completed exercise?', 'Its completed sets will also be deleted.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Remove', style: 'destructive', onPress: execute }]); else execute(); };
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><View style={styles.hero}><View><Text style={styles.title}>{workout.name}</Text><Text style={styles.muted}>{clock(elapsedSeconds(workout.startedAt, now))}</Text></View><AppButton label="Finish" onPress={requestFinish} /></View>
    <View style={styles.stats}><Stat value={String(workout.exercises.length)} label="Exercises" /><Stat value={String(summary.completedSets)} label="Sets done" /><Stat value={summary.totalVolume.toFixed(0)} label="Volume kg" /></View><RestTimer timer={timer} />
    <AppInput label="Workout notes" value={workoutNotes} onChangeText={setWorkoutNotes} onBlur={() => void updateWorkoutNotes(db, workout.id, workoutNotes.trim() || null)} placeholder="How did the session feel?" multiline />
    <AppButton label="Add Exercises" variant="secondary" onPress={() => router.push({ pathname: '/workout/add-exercises', params: { id: workout.id } })} />
    {workout.exercises.map((item, index) => <View key={item.id} style={styles.exercise}><View style={styles.exerciseHead}><View style={styles.exerciseTitle}><Text style={styles.exerciseName}>{item.exercise.name}</Text><Text style={styles.muted}>Target {item.targetSets ?? '—'} sets · {item.targetRepsMin ?? '—'}–{item.targetRepsMax ?? '—'} reps · Rest {item.restSeconds ?? 0}s</Text>{item.targetWeight != null ? <Text style={styles.muted}>Target weight {item.targetWeight} kg</Text> : null}{item.notes ? <Text style={styles.notes}>{item.notes}</Text> : null}<Text style={styles.placeholder}>Previous performance: coming with history</Text></View><ReorderControls canUp={index > 0} canDown={index < workout.exercises.length - 1} onUp={() => void move(index, -1)} onDown={() => void move(index, 1)} /></View>
      {item.sets.map((set, setIndex) => <WorkoutSetRow key={set.id} set={set} previous={item.sets[setIndex - 1]} onSave={async (value) => { await updateWorkoutSet(db, set.id, value); await load(); }} onDelete={() => void deleteWorkoutSet(db, set.id).then(load)} onComplete={(completed) => { if (completed && item.restSeconds) timer.start(item.restSeconds); }} />)}
      <View style={styles.row}><Pressable onPress={() => void addWorkoutSet(db, item.id).then(load)}><Text style={styles.link}>+ Add Set</Text></Pressable><Pressable onPress={() => void remove(item)}><Text style={styles.remove}>Remove Exercise</Text></Pressable></View></View>)}
  </ScrollView>;
}
function Stat({ value, label }: { value: string; label: string }) { return <View style={styles.stat}><Text style={styles.statValue}>{value}</Text><Text style={styles.statLabel}>{label}</Text></View>; }
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.background }, content: { padding: spacing.lg, paddingBottom: spacing.xxl, gap: spacing.md }, center: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.background }, hero: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, title: { ...typography.title, color: colors.text }, muted: { ...typography.caption, color: colors.textMuted }, stats: { flexDirection: 'row', gap: spacing.sm }, stat: { flex: 1, padding: spacing.md, borderRadius: radius.md, backgroundColor: colors.surface, alignItems: 'center' }, statValue: { ...typography.heading, color: colors.text }, statLabel: { ...typography.caption, color: colors.textMuted }, exercise: { padding: spacing.lg, borderRadius: radius.lg, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, gap: spacing.md }, exerciseHead: { flexDirection: 'row', justifyContent: 'space-between' }, exerciseTitle: { flex: 1 }, exerciseName: { ...typography.heading, color: colors.text }, notes: { ...typography.caption, color: colors.text, fontStyle: 'italic' }, placeholder: { ...typography.caption, color: colors.textMuted, marginTop: spacing.sm }, row: { flexDirection: 'row', justifyContent: 'space-between' }, link: { ...typography.label, color: colors.accent }, remove: { ...typography.label, color: colors.danger } });
