import { format } from 'date-fns'; import { router, useLocalSearchParams } from 'expo-router'; import { useEffect, useState } from 'react'; import { ActivityIndicator, ScrollView, StyleSheet, Text, View } from 'react-native';
import { AppButton } from '@/components/AppButton'; import { PersonalRecordBadge } from '@/components/PersonalRecordBadge'; import { colors } from '@/constants/colors'; import { radius, spacing } from '@/constants/spacing'; import { typography } from '@/constants/typography'; import { useDatabase } from '@/hooks/useDatabase'; import { getRecordsForWorkout } from '@/repositories/personalRecordRepository'; import { getWorkoutSummary } from '@/repositories/workoutRepository'; import type { PersonalRecord } from '@/types/personalRecord'; import type { WorkoutSummary } from '@/types/workout';
const duration = (seconds: number | null) => `${Math.floor((seconds ?? 0) / 60)} min`;
export default function WorkoutSummaryScreen() { const { id } = useLocalSearchParams<{ id: string }>(); const db = useDatabase(); const [summary, setSummary] = useState<WorkoutSummary | null>(); const [records, setRecords] = useState<PersonalRecord[]>([]); useEffect(() => { if (id) { void getWorkoutSummary(db, id).then(setSummary); void getRecordsForWorkout(db, id).then(setRecords); } }, [db, id]);
  if (summary === undefined) return <View style={styles.center}><ActivityIndicator color={colors.accent} /></View>; if (!summary) return <View style={styles.center}><Text style={styles.muted}>Summary not found.</Text></View>;
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><Text style={styles.success}>WORKOUT COMPLETE</Text><Text style={styles.title}>{summary.workout.name}</Text><Text style={styles.muted}>{format(new Date(summary.workout.startedAt), 'MMMM d, yyyy')} · {duration(summary.workout.durationSeconds)}</Text>
    <View style={styles.badgeRow}><PersonalRecordBadge records={records} /></View>
    <View style={styles.stats}><Stat value={String(summary.completedExercises)} label="Exercises" /><Stat value={String(summary.completedSets)} label="Sets" /><Stat value={String(summary.totalRepetitions)} label="Reps" /><Stat value={summary.totalVolume.toFixed(1)} label="kg volume" /></View>
    {summary.workout.exercises.filter((item) => item.sets.some((set) => set.completed)).map((item) => <View key={item.id} style={styles.card}><Text style={styles.exercise}>{item.exercise.name}</Text>{item.sets.filter((set) => set.completed).map((set) => <Text key={set.id} style={styles.muted}>Set {set.setNumber}: {set.weight ?? 0} kg × {set.reps ?? 0} reps · {set.setType}</Text>)}</View>)}
    <AppButton label="Done" onPress={() => router.replace('/')} /></ScrollView>; }
function Stat({ value, label }: { value: string; label: string }) { return <View style={styles.stat}><Text style={styles.statValue}>{value}</Text><Text style={styles.statLabel}>{label}</Text></View>; }
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.background }, content: { padding: spacing.lg, paddingBottom: spacing.xxl, gap: spacing.md, alignItems: 'stretch' }, badgeRow: { alignItems: 'center' }, center: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.background }, success: { ...typography.label, color: colors.accent, textAlign: 'center' }, title: { ...typography.title, color: colors.text, textAlign: 'center' }, muted: { ...typography.caption, color: colors.textMuted, textAlign: 'center' }, stats: { flexDirection: 'row', gap: spacing.sm, marginVertical: spacing.lg }, stat: { flex: 1, padding: spacing.sm, backgroundColor: colors.surface, borderRadius: radius.md, alignItems: 'center' }, statValue: { ...typography.heading, color: colors.text }, statLabel: { fontSize: 10, color: colors.textMuted }, card: { padding: spacing.lg, gap: spacing.sm, borderRadius: radius.lg, backgroundColor: colors.surface }, exercise: { ...typography.body, color: colors.text, fontWeight: '800' } });
