import { format } from 'date-fns'; import { router, useFocusEffect, useLocalSearchParams } from 'expo-router'; import { useCallback, useState } from 'react'; import { ActivityIndicator, Alert, ScrollView, StyleSheet, Text, View } from 'react-native';
import { AppButton } from '@/components/AppButton'; import { WorkoutHistoryCard } from '@/components/WorkoutHistoryCard'; import { colors } from '@/constants/colors'; import { radius, spacing } from '@/constants/spacing'; import { typography } from '@/constants/typography'; import { useDatabase } from '@/hooks/useDatabase'; import { archivePlan, deletePlan, duplicatePlan, getPlanById } from '@/repositories/workoutPlanRepository'; import { createWorkoutFromPlan, getCompletedWorkoutsPage } from '@/repositories/workoutRepository'; import { formatPlanTarget } from '@/services/workoutPlanService'; import type { WorkoutHistoryItem } from '@/types/workout'; import type { WorkoutPlanWithExercises } from '@/types/workoutPlan'; import { getUserMessage } from '@/utils/errors';
export default function PlanDetailsScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const db = useDatabase(); const [plan, setPlan] = useState<WorkoutPlanWithExercises | null>(); const [history, setHistory] = useState<WorkoutHistoryItem[]>([]); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { if (!id) return; const [nextPlan, nextHistory] = await Promise.all([getPlanById(db, id), getCompletedWorkoutsPage(db, { search: '', datePreset: 'all', planId: id }, 'newest', 0, 50)]); setPlan(nextPlan); setHistory(nextHistory); }, [db, id]); useFocusEffect(useCallback(() => { void load(); }, [load]));
  if (plan === undefined) return <View style={styles.center}><ActivityIndicator size="large" color={colors.accent} /></View>; if (!plan) return <View style={styles.center}><Text style={styles.muted}>Plan not found.</Text></View>;
  const perform = async (action: () => Promise<void>) => { setBusy(true); try { await action(); } catch (caught) { Alert.alert('Plan action failed', getUserMessage(caught)); } finally { setBusy(false); } };
  const duplicate = () => void perform(async () => { const copy = await duplicatePlan(db, plan.id); router.replace({ pathname: '/plans/[id]', params: { id: copy.id } }); });
  const start = () => void perform(async () => { const workoutId = await createWorkoutFromPlan(db, plan); router.push({ pathname: '/workout/active', params: { id: workoutId } }); });
  const archive = () => Alert.alert('Archive plan?', 'The plan will be hidden from the Plans tab.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Archive', onPress: () => void perform(async () => { await archivePlan(db, plan.id); router.back(); }) }]);
  const remove = () => Alert.alert('Delete plan?', 'This permanently deletes the plan. Exercises remain in your library.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Delete', style: 'destructive', onPress: () => void perform(async () => { await deletePlan(db, plan.id); router.back(); }) }]);
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><View style={styles.hero}><View style={[styles.dot, { backgroundColor: plan.color ?? colors.accent }]} /><Text style={styles.title}>{plan.name}</Text><Text style={styles.badge}>{plan.isBuiltin ? 'STARTER PLAN' : 'MY PLAN'}</Text>{plan.description ? <Text style={styles.description}>{plan.description}</Text> : null}<Text style={styles.meta}>{plan.exerciseCount} exercises · {plan.estimatedSetCount} estimated sets · Updated {format(new Date(plan.updatedAt), 'MMM d, yyyy')}</Text></View>
    {plan.exercises.map((item, index) => <View key={item.id} style={styles.exercise}><Text style={styles.order}>{index + 1}</Text><View style={styles.exerciseBody}><Text style={styles.exerciseName}>{item.exercise.name}</Text><Text style={styles.target}>{formatPlanTarget(item)}</Text>{item.restSeconds != null ? <Text style={styles.muted}>Rest {item.restSeconds}s</Text> : null}{item.notes ? <Text style={styles.notes}>{item.notes}</Text> : null}</View></View>)}
    {history.length > 0 && <View style={styles.historySection}>
      <Text style={styles.sectionTitle}>History</Text>
      <Text style={styles.muted}>Used {history.length}{history.length === 50 ? '+' : ''} time{history.length === 1 ? '' : 's'} · Last {format(new Date(history[0].startedAt), 'MMM d, yyyy')}</Text>
      {history.map((workout) => <WorkoutHistoryCard key={workout.id} workout={workout} onPress={() => router.push(`/workout/${workout.id}`)} />)}
    </View>}
    <AppButton label="Start Plan" loading={busy} onPress={start} />
    {!plan.isBuiltin && <AppButton label="Edit Plan" variant="secondary" onPress={() => router.push({ pathname: '/plans/edit/[id]', params: { id: plan.id } })} />}
    {!plan.isBuiltin && <AppButton label="Create Superset / Circuit" variant="secondary" onPress={()=>router.push({pathname:'/plans/groups/[id]',params:{id:plan.id}})}/>}
    <AppButton label="Duplicate Plan" variant="secondary" loading={busy} onPress={duplicate} /><AppButton label="Archive Plan" variant="secondary" onPress={archive} />
    {!plan.isBuiltin && <AppButton label="Delete Plan" variant="danger" onPress={remove} />}
  </ScrollView>;
}
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.background }, content: { padding: spacing.lg, paddingBottom: spacing.xxl, gap: spacing.md }, center: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: colors.background }, hero: { alignItems: 'center', gap: spacing.sm, paddingBottom: spacing.lg }, dot: { width: 18, height: 18, borderRadius: 9 }, title: { ...typography.title, color: colors.text, textAlign: 'center' }, badge: { fontSize: 11, color: colors.accent, fontWeight: '800' }, description: { ...typography.body, color: colors.textMuted, textAlign: 'center' }, meta: { ...typography.caption, color: colors.textMuted, textAlign: 'center' }, exercise: { flexDirection: 'row', padding: spacing.lg, gap: spacing.md, borderRadius: radius.lg, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border }, order: { color: colors.accent, fontWeight: '800' }, exerciseBody: { flex: 1, gap: 3 }, exerciseName: { ...typography.body, color: colors.text, fontWeight: '700' }, target: { ...typography.label, color: colors.text }, muted: { ...typography.caption, color: colors.textMuted }, notes: { ...typography.caption, color: colors.textMuted, fontStyle: 'italic' }, historySection: { gap: spacing.sm, marginTop: spacing.sm }, sectionTitle: { ...typography.heading, color: colors.text } });
