import { Ionicons } from '@expo/vector-icons'; import { router } from 'expo-router'; import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, FlatList, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { AppButton } from '@/components/AppButton'; import { EmptyState } from '@/components/EmptyState'; import { FilterChip } from '@/components/FilterChip'; import { SearchBar } from '@/components/SearchBar';
import { colors } from '@/constants/colors'; import { equipmentTypes, type EquipmentType } from '@/constants/equipmentTypes'; import { exerciseCategories, type ExerciseCategory } from '@/constants/exerciseCategories'; import { radius, spacing } from '@/constants/spacing'; import { typography } from '@/constants/typography';
import { usePlanDraft } from '@/contexts/PlanDraftContext'; import { useDatabase } from '@/hooks/useDatabase'; import { listExercises } from '@/repositories/exerciseRepository'; import type { Exercise } from '@/types/exercise'; import { getUserMessage } from '@/utils/errors';
export default function SelectPlanExercisesScreen() {
  const db = useDatabase(); const { draft, addExercises } = usePlanDraft(); const [items, setItems] = useState<Exercise[]>([]); const [selected, setSelected] = useState<Set<string>>(new Set());
  const [search, setSearch] = useState(''); const [category, setCategory] = useState<ExerciseCategory>(); const [equipment, setEquipment] = useState<EquipmentType>(); const [loading, setLoading] = useState(true); const [error, setError] = useState<string>();
  useEffect(() => { const timer = setTimeout(() => { void listExercises(db, { search, category, equipment }).then(setItems).catch((caught) => setError(getUserMessage(caught, 'Could not load exercises.'))).finally(() => setLoading(false)); }, 150); return () => clearTimeout(timer); }, [category, db, equipment, search]);
  const existing = useMemo(() => new Set(draft.exercises.map((item) => item.exerciseId)), [draft.exercises]);
  const toggle = (id: string) => setSelected((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; });
  const add = () => { addExercises(items.filter((item) => selected.has(item.id))); router.back(); };
  return <View style={styles.screen}><View style={styles.controls}><SearchBar value={search} onChangeText={setSearch} />
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}><FilterChip label="All categories" selected={!category} onPress={() => setCategory(undefined)} />{exerciseCategories.map((item) => <FilterChip key={item} label={item} selected={category === item} onPress={() => setCategory(item)} />)}</ScrollView>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}><FilterChip label="All equipment" selected={!equipment} onPress={() => setEquipment(undefined)} />{equipmentTypes.map((item) => <FilterChip key={item} label={item} selected={equipment === item} onPress={() => setEquipment(item)} />)}</ScrollView></View>
    {loading ? <ActivityIndicator style={styles.flex} color={colors.accent} /> : error ? <EmptyState title="Exercises unavailable" message={error} /> : <FlatList data={items} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} ItemSeparatorComponent={() => <View style={{ height: spacing.sm }} />}
      ListEmptyComponent={<EmptyState title="No exercises found" message="Try changing the search or filters." />} renderItem={({ item }) => { const already = existing.has(item.id); const checked = selected.has(item.id); return <Pressable disabled={already} onPress={() => toggle(item.id)} style={[styles.item, already && styles.disabled]}>
        <View style={styles.itemText}><Text style={styles.name}>{item.name}</Text><Text style={styles.meta}>{item.category} · {item.equipment}{already ? ' · Already added' : ''}</Text></View><Ionicons name={already || checked ? 'checkmark-circle' : 'ellipse-outline'} size={26} color={already || checked ? colors.accent : colors.textMuted} /></Pressable>; }} />}
    <View style={styles.footer}><AppButton label={`Add Selected (${selected.size})`} disabled={selected.size === 0} onPress={add} /></View></View>;
}
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.background }, controls: { padding: spacing.lg, gap: spacing.md }, chips: { gap: spacing.sm, paddingRight: spacing.lg }, flex: { flex: 1 }, list: { padding: spacing.lg, flexGrow: 1 }, item: { minHeight: 68, flexDirection: 'row', alignItems: 'center', padding: spacing.md, backgroundColor: colors.surface, borderRadius: radius.md, borderWidth: 1, borderColor: colors.border }, disabled: { opacity: .5 }, itemText: { flex: 1 }, name: { ...typography.body, color: colors.text, fontWeight: '700' }, meta: { ...typography.caption, color: colors.textMuted }, footer: { padding: spacing.lg, borderTopWidth: 1, borderTopColor: colors.border, backgroundColor: colors.background } });
